# 0.Library

In [31]:
import pandas as pd
from pathlib import Path

import importlib
import sys
sys.path.append('../') 
from features import data_utils as du
from features import data_pipeline as dp

# Reload
importlib.reload(du)
importlib.reload(dp)

# Constants and paths
parent_folder = Path("../..") # go 2 folder up: "../.."
data_folder = parent_folder / "data"
input_path_of_json = data_folder / "patients_data_log.json"
df_data_log = pd.read_json(input_path_of_json)

patient_ids = df_data_log["PatientID"].to_list()
patients_data_folder = data_folder / "PatientsData"

# 1.

In [20]:
patient_id = patient_ids[0]
patient_folder_path = du.find_patient_folder(patients_data_folder=patients_data_folder,
                                               patient_id=patient_id)
                                               
path_to_check = patient_folder_path / "clean_data"
clean_csv_files = du.find_csv_file(patient_folder_path / "clean_data")
clean_csv_files

['cleaned_20260502_113117_01_Tutorial_events.csv',
 'cleaned_20260502_113117_01_Tutorial_trajectory.csv',
 'cleaned_20260502_113117_02_ObjectRecognition_events.csv',
 'cleaned_20260502_113117_02_ObjectRecognition_trajectory.csv',
 'cleaned_20260502_113117_03_Visuospatial_events.csv',
 'cleaned_20260502_113117_03_Visuospatial_trajectory.csv',
 'cleaned_20260502_113117_04_Memory_events.csv',
 'cleaned_20260502_113117_04_Memory_trajectory.csv']

In [21]:
clean_df = pd.read_csv(path_to_check / clean_csv_files[0])

In [22]:
clean_df.head()

,Timestamp,PhaseTime_s,Section,EventType,ObjectName,Hand,IsCorrect,Duration_s,Distance_m,Details,Activity_Log
0,2026-05-02 11:31:17.628,0.000,Default,PHASE_START,NaN,NaN,NaN,0.0,0.0,Phase=01_Tutorial,"['Section=Default', 'SessionID=20260502_113117..."
1,2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,NaN,NaN,0.0,0.0,Section=Default,['Panel=WelcomePanel']
2,2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
3,2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
4,2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...

In [23]:
clean_df.columns

Index(['Timestamp', 'PhaseTime_s', 'Section', 'EventType', 'ObjectName',
       'Hand', 'IsCorrect', 'Duration_s', 'Distance_m', 'Details',
       'Activity_Log'],
      dtype='object')

In [24]:
section_names = clean_df['Section'].unique()
section_names

array(['Default', 'ButtonSelection', 'GrabPractice', 'Completion'],
      dtype=object)

In [33]:
section_df = du.extract_section(clean_df, section_names[0])
events_to_ignore =['PHASE_START','SECTION_END' ]

In [34]:
event_types = du.extract_event_types(section_df, events_to_ignore)
event_types

['PANEL_SHOWN',
 'BUTTON_HOVER_START',
 'BUTTON_HOVER_END',
 'BUTTON_PRESSED',
 'BUTTON_RELEASED',
 'PANEL_DISMISSED']

In [35]:
dict_hover_button = {
    'button_name' : None,
    'hover_count' : None,
    'hover_duration' : None
}

In [54]:
clean_df.head(30)

,Timestamp,PhaseTime_s,Section,EventType,ObjectName,Hand,IsCorrect,Duration_s,Distance_m,Details,Activity_Log
0,2026-05-02 11:31:17.628,0.000,Default,PHASE_START,NaN,NaN,NaN,0.000,0.0,Phase=01_Tutorial,"['Section=Default', 'SessionID=20260502_113117..."
1,2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,NaN,NaN,0.000,0.0,Section=Default,['Panel=WelcomePanel']
2,2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
3,2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
4,2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
5,2026-05-02 11:31:26.183,3.217,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
6,2026-05-02 11:31:26.378,3.411,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
7,2026-05-02 11:31:26.697,3.731,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
8,2026-05-02 11:31:28.907,5.940,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
9,2026-05-02 11:31:29.448,6.483,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
10,2026-05-02 11:31:35.603,12.637,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
11,2026-05-02 11:31:37.895,14.930,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
12,2026-05-02 11:31:38.423,15.457,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
13,2026-05-02 11:31:38.909,15.943,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
14,2026-05-02 11:31:39.381,16.415,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
15,2026-05-02 11:31:39.979,17.013,Default,BUTTON_PRESSED,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
16,2026-05-02 11:31:40.200,17.235,Default,BUTTON_RELEASED,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
17,2026-05-02 11:31:40.205,17.235,Default,PANEL_DISMISSED,WelcomePanel,NaN,NaN,17.235,0.0,Section=Default,"['Panel=WelcomePanel', 'ReadingTime=17.23s']"
18,2026-05-02 11:31:40.206,17.235,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
19,2026-05-02 11:31:40.208,17.235,Default,SECTION_END,NaN,NaN,NaN,17.235,0.0,Section=Default,['Duration=17.23s']
20,2026-05-02 11:31:40.208,17.235,ButtonSelection,SECTION_START,NaN,NaN,NaN,0.000,0.0,Section=ButtonSelection,['PhaseTime=17.23s']
21,2026-05-02 11:31:40.209,17.235,ButtonSelection,PANEL_SHOWN,ButtonInstructionPanel,NaN,NaN,0.000,0.0,Section=ButtonSelection,['Panel=ButtonInstructionPanel']
22,2026-05-02 11:31:40.209,17.235,ButtonSelection,BUTTON_CLICKED,NaN,NaN,NaN,0.000,0.0,Section=ButtonSelection,['Button=StartTutorialButton[TutorialWelcome]'...
23,2026-05-02 11:31:44.409,21.443,ButtonSelection,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=ButtonSelection,['Button=PracticeButton1[TutorialButtonSelecti...
24,2026-05-02 11:31:45.506,22.540,ButtonSelection,BUTTON_PRESSED,NaN,NaN,NaN,0.000,0.0,Section=ButtonSelection,['Button=PracticeButton1[TutorialButtonSelecti...
25,2026-05-02 11:31:45.659,22.693,ButtonSelection,BUTTON_RELEASED,NaN,NaN,NaN,0.000,0.0,Section=ButtonSelection,['Button=PracticeButton1[TutorialButtonSelecti...
26,2026-05-02 11:31:45.660,22.693,ButtonSelection,BUTTON_PRESSED,NaN,NaN,NaN,0.000,0.0,Section=ButtonSelection,"['Button=1', 'PressCount=1']"
27,2026-05-02 11:31:45.661,22.693,ButtonSelection,BUTTON_CLICKED,NaN,NaN,NaN,0.000,0.0,Section=ButtonSelection,['Button=PracticeButton1[TutorialButtonSelecti...
28,2026-05-02 11:31:45.923,22.956,ButtonSelection,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=ButtonSelection,['Button=PracticeButton1[TutorialButtonSelecti...
29,2026-05-02 11:31:46.130,23.165,ButtonSelection,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=ButtonSelection,['Button=PracticeButton2[TutorialButtonSelecti...

In [51]:
section_df

,Timestamp,PhaseTime_s,Section,EventType,ObjectName,Hand,IsCorrect,Duration_s,Distance_m,Details,Activity_Log
0,2026-05-02 11:31:17.628,0.000,Default,PHASE_START,NaN,NaN,NaN,0.000,0.0,Phase=01_Tutorial,"['Section=Default', 'SessionID=20260502_113117..."
1,2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,NaN,NaN,0.000,0.0,Section=Default,['Panel=WelcomePanel']
2,2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
3,2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
4,2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
5,2026-05-02 11:31:26.183,3.217,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
6,2026-05-02 11:31:26.378,3.411,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
7,2026-05-02 11:31:26.697,3.731,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
8,2026-05-02 11:31:28.907,5.940,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
9,2026-05-02 11:31:29.448,6.483,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
10,2026-05-02 11:31:35.603,12.637,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
11,2026-05-02 11:31:37.895,14.930,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
12,2026-05-02 11:31:38.423,15.457,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
13,2026-05-02 11:31:38.909,15.943,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
14,2026-05-02 11:31:39.381,16.415,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
15,2026-05-02 11:31:39.979,17.013,Default,BUTTON_PRESSED,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
16,2026-05-02 11:31:40.200,17.235,Default,BUTTON_RELEASED,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
17,2026-05-02 11:31:40.205,17.235,Default,PANEL_DISMISSED,WelcomePanel,NaN,NaN,17.235,0.0,Section=Default,"['Panel=WelcomePanel', 'ReadingTime=17.23s']"
18,2026-05-02 11:31:40.206,17.235,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.000,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
19,2026-05-02 11:31:40.208,17.235,Default,SECTION_END,NaN,NaN,NaN,17.235,0.0,Section=Default,['Duration=17.23s']

In [53]:
df2 = section_df[section_df["EventType"].isin(["BUTTON_HOVER_START", "BUTTON_HOVER_END"])].copy()

df2

,Timestamp,PhaseTime_s,Section,EventType,ObjectName,Hand,IsCorrect,Duration_s,Distance_m,Details,Activity_Log
2,2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
3,2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
4,2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
5,2026-05-02 11:31:26.183,3.217,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
6,2026-05-02 11:31:26.378,3.411,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
7,2026-05-02 11:31:26.697,3.731,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
8,2026-05-02 11:31:28.907,5.940,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
9,2026-05-02 11:31:29.448,6.483,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
10,2026-05-02 11:31:35.603,12.637,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
11,2026-05-02 11:31:37.895,14.930,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
12,2026-05-02 11:31:38.423,15.457,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
13,2026-05-02 11:31:38.909,15.943,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
14,2026-05-02 11:31:39.381,16.415,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
18,2026-05-02 11:31:40.206,17.235,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...

In [57]:
df2["hover_id"] = (df2["EventType"] == "BUTTON_HOVER_START").cumsum()
df2[["EventType", "hover_id"]]

             EventType  hover_id
2   BUTTON_HOVER_START         1
3     BUTTON_HOVER_END         1
4   BUTTON_HOVER_START         2
5     BUTTON_HOVER_END         2
6   BUTTON_HOVER_START         3
7     BUTTON_HOVER_END         3
8   BUTTON_HOVER_START         4
9     BUTTON_HOVER_END         4
10  BUTTON_HOVER_START         5
11    BUTTON_HOVER_END         5
12  BUTTON_HOVER_START         6
13    BUTTON_HOVER_END         6
14  BUTTON_HOVER_START         7
18    BUTTON_HOVER_END         7

In [58]:
starts = df2[df2["EventType"] == "BUTTON_HOVER_START"].copy()
ends = df2[df2["EventType"] == "BUTTON_HOVER_END"].copy()

In [59]:
starts

,Timestamp,PhaseTime_s,Section,EventType,ObjectName,Hand,IsCorrect,Duration_s,Distance_m,Details,Activity_Log,hover_id
2,2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...,1
4,2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...,2
6,2026-05-02 11:31:26.378,3.411,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...,3
8,2026-05-02 11:31:28.907,5.940,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...,4
10,2026-05-02 11:31:35.603,12.637,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...,5
12,2026-05-02 11:31:38.423,15.457,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...,6
14,2026-05-02 11:31:39.381,16.415,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...,7

In [60]:
merged = starts.merge(
    ends,
    on="hover_id",
    suffixes=("_start", "_end")
)

In [62]:
merged

,Timestamp_start,PhaseTime_s_start,Section_start,EventType_start,ObjectName_start,Hand_start,IsCorrect_start,Duration_s_start,Distance_m_start,Details_start,...,PhaseTime_s_end,Section_end,EventType_end,ObjectName_end,Hand_end,IsCorrect_end,Duration_s_end,Distance_m_end,Details_end,Activity_Log_end
0,2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,...,0.952,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
1,2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,...,3.217,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
2,2026-05-02 11:31:26.378,3.411,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,...,3.731,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
3,2026-05-02 11:31:28.907,5.940,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,...,6.483,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
4,2026-05-02 11:31:35.603,12.637,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,...,14.930,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
5,2026-05-02 11:31:38.423,15.457,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,...,15.943,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
6,2026-05-02 11:31:39.381,16.415,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,...,17.235,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...

In [49]:
section_df[section_df['EventType'].str.startswith('BUTTON_HOVER')][[ 'EventType', 'Activity_Log' ]]

             EventType                                       Activity_Log
2   BUTTON_HOVER_START  ['Button=StartTutorialButton[TutorialWelcome]'...
3     BUTTON_HOVER_END  ['Button=StartTutorialButton[TutorialWelcome]'...
4   BUTTON_HOVER_START  ['Button=StartTutorialButton[TutorialWelcome]'...
5     BUTTON_HOVER_END  ['Button=StartTutorialButton[TutorialWelcome]'...
6   BUTTON_HOVER_START  ['Button=StartTutorialButton[TutorialWelcome]'...
7     BUTTON_HOVER_END  ['Button=StartTutorialButton[TutorialWelcome]'...
8   BUTTON_HOVER_START  ['Button=StartTutorialButton[TutorialWelcome]'...
9     BUTTON_HOVER_END  ['Button=StartTutorialButton[TutorialWelcome]'...
10  BUTTON_HOVER_START  ['Button=StartTutorialButton[TutorialWelcome]'...
11    BUTTON_HOVER_END  ['Button=StartTutorialButton[TutorialWelcome]'...
12  BUTTON_HOVER_START  ['Button=StartTutorialButton[TutorialWelcome]'...
13    BUTTON_HOVER_END  ['Button=StartTutorialButton[TutorialWelcome]'...
14  BUTTON_HOVER_START  ['Button=StartTutorialButton[TutorialWelcome]'...
18    BUTTON_HOVER_END  ['Button=StartTutorialButton[TutorialWelcome]'...

In [50]:
idx = section_df[section_df["EventType"].isin(["BUTTON_HOVER_START", "BUTTON_HOVER_END"])].index
idx_list = idx.tolist()
idx_list

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 18]

In [45]:
clean_df[clean_df['EventType'] == 'BUTTON_HOVER_START'].iloc[0]['Activity_Log']

"['Button=StartTutorialButton[TutorialWelcome]', 'HoverCount=1']"

In [46]:
clean_df[clean_df['EventType'] == 'BUTTON_HOVER_END'].iloc[0]['Activity_Log']

"['Button=StartTutorialButton[TutorialWelcome]', 'HoverDuration=0.95s']"