# 0.Library

In [62]:
import pandas as pd
from pathlib import Path

import importlib
import sys
sys.path.append('../') 
from features import data_utils as du
from features import data_pipeline as dp

# Reload
importlib.reload(du)
importlib.reload(dp)

# Constants and paths
parent_folder = Path("../..") # go 2 folder up= "../.."
data_folder = parent_folder / "data"
input_path_of_json = data_folder / "patients_data_log.json"
df_data_log = pd.read_json(input_path_of_json)

patient_ids = df_data_log["PatientID"].to_list()
patients_data_folder = data_folder / "PatientsData"

# 1. Phase-Level Feature vectors structure
same as in Readme.md

In [5]:
features_dict = {
    "phase_id": None,
    "phase_name": None,
    "phase_duration": None,
}

## 1.1 Events file

In [6]:
# statistical features
reading_time_dict = {
    "total_reading_time": None,
    "mean_reading_time": None,
    "max_reading_time": None,
    "median_reading_time": None,
    "std_reading_time": None,
    "intensity_reading_time" : None
}

hover_dict = {
    "total_count_hover": None,
    "total_duration_hover": None,
    "mean_duration_hover": None,
    "max_duration_hover": None,
    "median_duration_hover": None,
    "std_duration_hover": None,
    "intensity_hover": None
}

press_dict = {
    "total_count_press": None,
    "total_duration_press": None,
    "mean_duration_press": None,
    "max_duration_press": None,
    "median_duration_press": None,
    "std_duration_press": None,
    "intensity_press": None # Interaction intensity
}

grab_dict = {
    "total_count_grab": None,
    "total_duration_grab": None,
    "mean_duration_grab": None,
    "max_duration_grab": None,
    "median_duration_grab": None,
    "std_duration_grab": None,
    "intensity_grab": None # Interaction intensity
}

gaze_dict = {
    "total_count_gaze": None,
    "total_duration_gaze": None,
    "mean_duration_gaze": None,
    "max_duration_gaze": None,
    "median_duration_gaze": None,
    "std_duration_gaze": None,
    "intensity_gaze": None # Interaction intensity
}

# Behavioral features
behavior_dict = {
    "hover_vs_reading_time_ratio": None,
    "hover_vs_active_interaction_ratio": None,
    "interaction_fraction": None,
    "decision_latency": None,  
    "clicks_per_second": None,
    "hovers_per_click": None
}

# Temporal Features
temporal_dict = {
    "time_before_first_press": None,
    "time_before_first_hover": None
}

## 1.2 Trajectory file

In [7]:
# Head features
headset_dict = {
    # Position features
    "head_total_distance": None,

    "HMD_X_std": None,
    "HMD_Y_std": None,
    "HMD_Z_std": None,

    "HMD_X_range": None,
    "HMD_Y_range": None,
    "HMD_Z_range": None,

    # Speed features
    "mean_head_speed": None,
    "max_head_speed": None,
    "std_head_speed": None,

    # Orientation features
    "Yaw_std": None,
    "Pitch_std": None,
    "Roll_std": None,
    "Yaw_range": None,
    "Pitch_range": None,
    "Roll_range": None,

    # Exploration features
    "exploration_index": None,

    # Gaze features
    "gaze_target_counts": None,
    "gaze_switch_count": None

}

# Hand features
controller_dict = {
    # Distance features
    "dominant_hand_total_distance": None,
    "not_dominant_hand_total_distance": None,

    # Speed features
    "dominant_hand_mean_speed": None,
    "not_dominant_hand_mean_speed": None,
    "dominant_hand_max_speed": None,
    "not_dominant_hand_max_speed": None,

    # Workspace_volume features
    "dominant_hand_x_range": None,
    "dominant_hand_y_range": None,
    "dominant_hand_z_range": None,
    "not_dominant_hand_x_range": None,
    "not_dominant_hand_y_range": None,
    "not_dominant_hand_z_range": None,

    # Active time features
    "dominant_hand_trigger_active_time": None,
    "not_dominant_hand_trigger_active_time": None,

    # Press count features
    "dominant_hand_trigger_press_count": None,
    "not_dominant_hand_trigger_press_count": None,

    # Grab count features
    "dominant_hand_grab_count": None,
    "not_dominant_hand_grab_count": None,

    # Grib duration features
    "dominant_hand_grab_duration": None,
    "not_dominant_hand_grab_duration": None,

    # Symmetry feature
    "hand_movement_symmetry": None
}

# 2. Paitent-Level Feature vectors structure
same as in Readme.md

In [2]:
global_feature_dict = {
    "object_recognition_accuracy":None,
    "recognition_response_time_mean":None,
    "recognition_response_time_per_round":None,
    "visuospatial_placements_correct":None,
    "socket_rejection_count":None,
    "memory_recall_accuracy":None,
    "mean_recall_latency":None,
    "mean_placement_error_distance":None,
    "carry_time_per_object":None,
    "pickup_count_per_object":None,
    "cognitive_freeze_count":None,
    "cognitive_freeze_duration":None,
    "re-grab_delay_after_rejection":None,
    "gazed_correct_socket_after_rejection":None,
    "hover_count_before_grab":None,
    "recall_first_action_delay":None,
    "hand_path_length":None,
    "hand_speed_mean":None,
    "hand_speed_peak":None,
    "hand_jitter":None,
    "head_path_length":None,
    "total_yaw":None,
    "gaze_on_target_percentage":None,
    "gaze_switch_count":None,
}

# 3. Final dataframe (example)

In [246]:
paitent_dict = {
    "Paitent_id" : None,
    "Age" : None,
    "Gender" : None,
    "Sessions_Completed_out_of_4" : None,
    "Help_Rating_out_of_5" : None,
}

paitent_dict.update(features_dict)
paitent_dict.update(reading_time_dict)
paitent_dict.update(hover_dict)
paitent_dict.update(press_dict)
paitent_dict.update(grab_dict)
paitent_dict.update(gaze_dict)
paitent_dict.update(behavior_dict)
paitent_dict.update(temporal_dict)
paitent_dict.update(headset_dict)
paitent_dict.update(controller_dict)
paitent_dict.update(global_feature_dict)

In [247]:
df = pd.DataFrame(columns=paitent_dict.keys())
for i in range(10):
    new_row = pd.DataFrame([paitent_dict])
    df = pd.concat([df, new_row], ignore_index=True)
df

,Paitent_id,Age,Gender,Sessions_Completed_out_of_4,Help_Rating_out_of_5,phase_id,phase_name,phase_duration,total_reading_time,mean_reading_time,...,gazed_correct_socket_after_rejection,hover_count_before_grab,recall_first_action_delay,hand_path_length,hand_speed_mean,hand_speed_peak,hand_jitter,head_path_length,total_yaw,gaze_on_target_percentage
0,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
7,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

# 4. Fill out Dictionaries for one paitent

## 4.1 Get dataset paths

In [4]:
# get clean path of one patient (all csv files)
patient_id = patient_ids[0]
patient_folder_path = du.find_patient_folder(patients_data_folder=patients_data_folder,
                                               patient_id=patient_id)
                                               
path_to_check = patient_folder_path / "clean_data"
csv_files_list = du.find_csv_file(patient_folder_path / "clean_data")
csv_files_list

['cleaned_20260502_113117_01_Tutorial_events.csv',
 'cleaned_20260502_113117_01_Tutorial_trajectory.csv',
 'cleaned_20260502_113117_02_ObjectRecognition_events.csv',
 'cleaned_20260502_113117_02_ObjectRecognition_trajectory.csv',
 'cleaned_20260502_113117_03_Visuospatial_events.csv',
 'cleaned_20260502_113117_03_Visuospatial_trajectory.csv',
 'cleaned_20260502_113117_04_Memory_events.csv',
 'cleaned_20260502_113117_04_Memory_trajectory.csv']

## 4.2 Phase-Level dictionary

### 4.2.1 Phase 0 : Tutorial phase_events

In [249]:
df = pd.read_csv(path_to_check / csv_files_list[0])
df.head()

,Timestamp,PhaseTime_s,Section,EventType,ObjectName,Hand,IsCorrect,Duration_s,Distance_m,Details,Activity_Log
0,2026-05-02 11:31:17.628,0.000,Default,PHASE_START,NaN,NaN,NaN,0.0,0.0,Phase=01_Tutorial,"['Section=Default', 'SessionID=20260502_113117..."
1,2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,NaN,NaN,0.0,0.0,Section=Default,['Panel=WelcomePanel']
2,2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
3,2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...
4,2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,['Button=StartTutorialButton[TutorialWelcome]'...

#### Fill out feature dict

In [250]:
features_dict["phase_id"] = 1
features_dict["phase_name"] = "toturial"
features_dict["phase_duration"] = du.extract_phase_duration(df)

dominant_hand = df['Hand'].unique()
features_dict

{'phase_id': 1, 'phase_name': 'toturial', 'phase_duration': np.float64(49.04)}

#### Fill out reading_time_dict

In [251]:
reading_time_series = df['Activity_Log'].apply(du.extract_value_from_string,pattern_list=[r"ReadingTime=([0-9]*\.?[0-9]+)"])

In [252]:
# cleaning
reading_time_series = reading_time_series.dropna()
reading_time_series = reading_time_series.astype(float)
reading_time_series

17    17.23
33     6.80
71    21.00
Name: Activity_Log, dtype: float64

In [253]:
reading_time_dict['total_reading_time'], reading_time_dict['mean_reading_time'], reading_time_dict['max_reading_time'], reading_time_dict['median_reading_time'], reading_time_dict['std_reading_time']=du.calculate_duration_metric_stats(metric_series=reading_time_series)

In [254]:
reading_time_dict['intensity_reading_time']=du.ratio_calculation(value1=reading_time_dict['total_reading_time'],
                                                    value2=features_dict["phase_duration"])

In [255]:
reading_time_dict

{'total_reading_time': np.float64(45.03),
 'mean_reading_time': np.float64(15.01),
 'max_reading_time': np.float64(21.0),
 'median_reading_time': np.float64(17.23),
 'std_reading_time': np.float64(7.36),
 'intensity_reading_time': np.float64(0.92)}

#### Fill out hover_dict

In [256]:
patterns = [r"HoverCount=([0-9]+)", 
            r"TotalHovers=([0-9]+)"]


hover_series = df['Activity_Log'].apply(du.extract_value_from_string,pattern_list=patterns)

In [257]:
hover_series = hover_series.dropna()
hover_series = hover_series.astype(float)

In [258]:
hover_dict['total_count_hover'] = int(du.calculate_counting_metric_stats(metric_series=hover_series))

In [259]:
patterns = [r"HoverDuration=([0-9]*\.?[0-9]+)"]

hover_series = df['Activity_Log'].apply(du.extract_value_from_string,pattern_list=patterns)

In [260]:
hover_series = hover_series.dropna()
hover_series = hover_series.astype(float)

In [261]:
hover_dict['total_duration_hover'], hover_dict['max_duration_hover'], hover_dict['mean_duration_hover'], hover_dict['median_duration_hover'], hover_dict['std_duration_hover'] =du.calculate_duration_metric_stats(metric_series=hover_series)

In [262]:
hover_dict['intensity_hover'] = round(hover_dict['total_duration_hover']/features_dict["phase_duration"],2)

In [263]:
hover_dict

{'total_count_hover': 32,
 'total_duration_hover': np.float64(20.64),
 'mean_duration_hover': np.float64(2.29),
 'max_duration_hover': np.float64(1.03),
 'median_duration_hover': np.float64(0.91),
 'std_duration_hover': np.float64(0.74),
 'intensity_hover': np.float64(0.42)}

#### Fill out press_dict

In [264]:
press_df = df[df['EventType'].isin(['BUTTON_PRESSED','BUTTON_CLICKED'])]
press_dict['total_count_press']=len(press_df)

In [265]:
patterns = [r"PressDuration=([0-9]*\.?[0-9]+)"]
press_series = df['Activity_Log'].apply(du.extract_value_from_string,pattern_list=patterns)
press_series = hover_series.dropna()
press_series = hover_series.astype(float)

In [266]:
press_dict['total_duration_press'], press_dict['max_duration_press'], press_dict['mean_duration_press'], press_dict['median_duration_press'], press_dict['std_duration_press'] =du.calculate_duration_metric_stats(metric_series=press_series)

In [267]:
press_dict['intensity_press'] = round(press_dict['total_duration_press']/features_dict["phase_duration"],2)

press_dict

{'total_count_press': 8,
 'total_duration_press': np.float64(20.64),
 'mean_duration_press': np.float64(2.29),
 'max_duration_press': np.float64(1.03),
 'median_duration_press': np.float64(0.91),
 'std_duration_press': np.float64(0.74),
 'intensity_press': np.float64(0.42)}

#### Fill out grab_dict

In [268]:
grab_df = df[df['EventType'].isin(['GRAB_RELEASE','GRAB_PRACTICE_PLACEMENT'])]
grab_dict['total_count_grab']=len(grab_df)

In [269]:
grab_series = df[df['EventType'].isin(['GRAB_RELEASE'])]['Duration_s']

grab_dict['total_duration_grab'], grab_dict['max_duration_grab'], grab_dict['mean_duration_grab'], grab_dict['median_duration_grab'], grab_dict['std_duration_grab'] =du.calculate_duration_metric_stats(metric_series=grab_series)

grab_dict['intensity_grab'] = round(grab_dict['total_duration_grab']/features_dict["phase_duration"],2)

grab_dict

{'total_count_grab': 7,
 'total_duration_grab': np.float64(5.58),
 'mean_duration_grab': np.float64(1.49),
 'max_duration_grab': np.float64(1.4),
 'median_duration_grab': np.float64(1.49),
 'std_duration_grab': np.float64(0.18),
 'intensity_grab': np.float64(0.11)}

#### Fill out gaze_dict

In [270]:
gaze_df = df[df['EventType'].isin(['GAZE_END'])]
gaze_dict['total_count_gaze'] = len(gaze_df)

In [271]:
patterns = [r"DwellTime=([0-9]*\.?[0-9]+)"]
gaze_series = df['Activity_Log'].apply(du.extract_value_from_string,pattern_list=patterns)
gaze_series = gaze_series.dropna()
gaze_series = gaze_series.astype(float)

In [272]:
gaze_dict['total_duration_gaze'], gaze_dict['max_duration_gaze'], gaze_dict['mean_duration_gaze'], gaze_dict['median_duration_gaze'], gaze_dict['std_duration_gaze'] =du.calculate_duration_metric_stats(metric_series=gaze_series)

gaze_dict['intensity_gaze'] = round(gaze_dict['total_duration_gaze']/features_dict["phase_duration"],2)

gaze_dict

{'total_count_gaze': 2,
 'total_duration_gaze': np.float64(0.44),
 'mean_duration_gaze': np.float64(0.22),
 'max_duration_gaze': np.float64(0.22),
 'median_duration_gaze': np.float64(0.22),
 'std_duration_gaze': np.float64(0.0),
 'intensity_gaze': np.float64(0.01)}

#### Fill out behavior_dict

In [273]:
first_hover_time = du.extract_event_first_time(df, ['BUTTON_HOVER_START'])
first_press_time = du.extract_event_first_time(df, ['BUTTON_PRESSED','BUTTON_CLICKED'])

In [274]:
behavior_dict["hover_vs_active_interaction_ratio"] = du.ratio_calculation(hover_dict["total_duration_hover"], press_dict["total_duration_press"])
behavior_dict["hover_vs_reading_time_ratio"] = du.ratio_calculation(hover_dict["total_duration_hover"], reading_time_dict["total_reading_time"])

behavior_dict["interaction_fraction"] = du.ratio_calculation(hover_dict["total_duration_hover"] + press_dict["total_duration_press"], features_dict['phase_duration'])

behavior_dict["decision_latency"] = du.calculate_decision_latency(first_hover_time, first_press_time)

behavior_dict["clicks_per_second"] = du.ratio_calculation(press_dict["total_count_press"], features_dict['phase_duration'])
behavior_dict["hovers_per_click"] = du.ratio_calculation(hover_dict["total_count_hover"], press_dict["total_count_press"])

behavior_dict

{'hover_vs_reading_time_ratio': np.float64(0.46),
 'hover_vs_active_interaction_ratio': np.float64(1.0),
 'interaction_fraction': np.float64(0.84),
 'decision_latency': np.float64(17.013),
 'clicks_per_second': np.float64(0.16),
 'hovers_per_click': 4.0}

#### Fill out temporal_dict

In [275]:
temporal_dict['time_before_first_press'] = first_press_time
temporal_dict['time_before_first_hover'] = first_hover_time

#### Merge all dictionaries of Events phase

In [276]:
features_dict.update(reading_time_dict)
features_dict.update(hover_dict)
features_dict.update(press_dict)
features_dict.update(grab_dict)
features_dict.update(gaze_dict)
features_dict.update(behavior_dict)
features_dict.update(temporal_dict)

features_dict

{'phase_id': 1,
 'phase_name': 'toturial',
 'phase_duration': np.float64(49.04),
 'total_reading_time': np.float64(45.03),
 'mean_reading_time': np.float64(15.01),
 'max_reading_time': np.float64(21.0),
 'median_reading_time': np.float64(17.23),
 'std_reading_time': np.float64(7.36),
 'intensity_reading_time': np.float64(0.92),
 'total_count_hover': 32,
 'total_duration_hover': np.float64(20.64),
 'mean_duration_hover': np.float64(2.29),
 'max_duration_hover': np.float64(1.03),
 'median_duration_hover': np.float64(0.91),
 'std_duration_hover': np.float64(0.74),
 'intensity_hover': np.float64(0.42),
 'total_count_press': 8,
 'total_duration_press': np.float64(20.64),
 'mean_duration_press': np.float64(2.29),
 'max_duration_press': np.float64(1.03),
 'median_duration_press': np.float64(0.91),
 'std_duration_press': np.float64(0.74),
 'intensity_press': np.float64(0.42),
 'total_count_grab': 7,
 'total_duration_grab': np.float64(5.58),
 'mean_duration_grab': np.float64(1.49),
 'max_duration_grab': np.float64(1.4),
 'median_duration_grab': np.float64(1.49),
 'std_duration_grab': np.float64(0.18),
 'intensity_grab': np.float64(0.11),
 'total_count_gaze': 2,
 'total_duration_gaze': np.float64(0.44),
 'mean_duration_gaze': np.float64(0.22),
 'max_duration_gaze': np.float64(0.22),
 'median_duration_gaze': np.float64(0.22),
 'std_duration_gaze': np.float64(0.0),
 'intensity_gaze': np.float64(0.01),
 'hover_vs_reading_time_ratio': np.float64(0.46),
 'hover_vs_active_interaction_ratio': np.float64(1.0),
 'interaction_fraction': np.float64(0.84),
 'decision_latency': np.float64(17.013),
 'clicks_per_second': np.float64(0.16),
 'hovers_per_click': 4.0,
 'time_before_first_press': np.float64(17.013),
 'time_before_first_hover': np.float64(0.0)}

### 4.2.2 Phase 0 : Tutorial phase_toturial

In [277]:
# Head features
headset_dict = {
    # Position features
    "head_total_distance": None,

    "HMD_X_std": None,
    "HMD_Y_std": None,
    "HMD_Z_std": None,

    "HMD_X_range": None,
    "HMD_Y_range": None,
    "HMD_Z_range": None,

    # Speed features in distance
    "mean_head_speed_in_distance": None,
    "max_head_speed_in_distance": None,
    "std_head_speed_in_distance": None,

    # Orientation features 
    "head_total_orientation": None,

    "Yaw_std": None,
    "Pitch_std": None,
    "Roll_std": None,

    "Yaw_range": None,
    "Pitch_range": None,
    "Roll_range": None,

    # Speed features in orientation
    "mean_head_speed_in_orientation": None,
    "max_head_speed_in_orientation": None,
    "std_head_speed_in_orientation": None,

    # Gaze features
    "gaze_obj_looked_ratio": None, # any target
    "gaze_switch_count": None

}

In [278]:
df = pd.read_csv(path_to_check / csv_files_list[1])
df.head()

,Timestamp,PhaseTime_s,Section,HMD_X,HMD_Y,HMD_Z,HMD_Pitch,HMD_Yaw,HMD_Roll,LeftCtrl_X,...,LeftTrigger,LeftGrip,RightCtrl_X,RightCtrl_Y,RightCtrl_Z,RightTrigger,RightGrip,FPS,GazeTarget,GazeDistance_m
0,2026-05-02 11:31:22.382,0.000,Default,-0.4961,2.7418,-0.0594,1.11,119.29,357.16,-0.1053,...,0.0,0.0,-0.1684,2.3923,-0.2882,0.0,0.0,65.5,NaN,0.0
1,2026-05-02 11:31:23.093,0.115,Default,-0.4177,1.5982,0.0098,354.88,98.06,357.39,-0.0186,...,0.0,0.0,-0.0307,1.2362,-0.0206,0.0,0.0,21.1,NaN,0.0
2,2026-05-02 11:31:23.190,0.223,Default,-0.4209,1.5973,0.0100,355.52,98.09,357.13,-0.0186,...,0.0,0.0,-0.0290,1.2365,-0.0222,0.0,0.0,67.9,NaN,0.0
3,2026-05-02 11:31:23.289,0.324,Default,-0.4212,1.5947,0.0116,357.37,97.32,357.17,-0.0184,...,0.0,0.0,-0.0277,1.2363,-0.0228,0.0,0.0,70.9,NaN,0.0
4,2026-05-02 11:31:23.401,0.435,Default,-0.4202,1.5961,0.0148,356.23,95.37,357.25,-0.0186,...,0.0,0.0,-0.0268,1.2361,-0.0247,0.0,0.0,71.3,NaN,0.0

#### Fill out headset_dict

In [279]:
headset_dict['head_total_distance'] = du.calculate_total_head_distance(df)

In [280]:
headset_dict['HMD_X_std'] = round(df['HMD_X'].std(),2)
headset_dict['HMD_Y_std'] = round(df['HMD_Y'].std(),2)
headset_dict['HMD_Z_std'] = round(df['HMD_Z'].std(),2)

In [281]:
headset_dict['HMD_X_range'] = round(df['HMD_X'].max() - df['HMD_X'].min(),2)
headset_dict['HMD_Y_range'] = round(df['HMD_Y'].max() - df['HMD_Y'].min(),2)
headset_dict['HMD_Z_range'] = round(df['HMD_Z'].max() - df['HMD_Z'].min(),2)

In [282]:
headset_dict['mean_head_speed_in_distance'], headset_dict['max_head_speed_in_distance'], headset_dict['std_head_speed_in_distance'] = du.calculate_head_distance_speed_metrics(df)

In [283]:
headset_dict["head_total_orientation"] = du.calculate_total_head_orientation(df)

In [284]:
headset_dict['Yaw_std']   = round(df['HMD_Yaw'].std(),2)
headset_dict['Pitch_std'] = round(df['HMD_Pitch'].std(),2)
headset_dict['Roll_std']  = round(df['HMD_Roll'].std(),2)

In [285]:
headset_dict['Yaw_range']   = round(df['HMD_Yaw'].max() - df['HMD_Yaw'].min(),2)
headset_dict['Pitch_range'] = round(df['HMD_Pitch'].max() - df['HMD_Pitch'].min(),2)
headset_dict['Roll_range']  = round(df['HMD_Roll'].max() - df['HMD_Roll'].min(),2)

In [286]:
headset_dict['mean_head_speed_in_orientation'], headset_dict['max_head_speed_in_orientation'], headset_dict['std_head_speed_in_orientation'] = du.calculate_head_orientation_speed_metrics(df)

In [287]:
not_none_GazeTarget = df['GazeTarget'].notna().sum()

headset_dict['gaze_obj_looked_ratio']= du.ratio_calculation(not_none_GazeTarget,len(df))

In [288]:
headset_dict['gaze_switch_count'] = du.calculate_switch_count(df)

In [289]:
headset_dict

{'head_total_distance': np.float64(2.09),
 'HMD_X_std': np.float64(0.03),
 'HMD_Y_std': np.float64(0.06),
 'HMD_Z_std': np.float64(0.02),
 'HMD_X_range': np.float64(0.15),
 'HMD_Y_range': np.float64(1.16),
 'HMD_Z_range': np.float64(0.19),
 'mean_head_speed_in_distance': np.float64(0.04),
 'max_head_speed_in_distance': np.float64(10.0),
 'std_head_speed_in_distance': np.float64(0.48),
 'head_total_orientation': np.float64(12327.97),
 'Yaw_std': np.float64(7.0),
 'Pitch_std': np.float64(139.91),
 'Roll_std': np.float64(126.73),
 'Yaw_range': np.float64(51.55),
 'Pitch_range': np.float64(359.68),
 'Roll_range': np.float64(359.99),
 'mean_head_speed_in_orientation': np.float64(251.1),
 'max_head_speed_in_orientation': np.float64(3271.91),
 'std_head_speed_in_orientation': np.float64(847.45),
 'gaze_obj_looked_ratio': np.float64(0.01),
 'gaze_switch_count': 0}

#### Fill out controller_dict

In [290]:
# Hand features
controller_dict = {
    # Distance features
    "dominant_hand_total_distance": None,
    "not_dominant_hand_total_distance": None,

    # Speed features
    "dominant_hand_mean_speed": None,
    "not_dominant_hand_mean_speed": None,
    "dominant_hand_max_speed": None,
    "not_dominant_hand_max_speed": None,

    # Workspace_volume features
    "dominant_hand_x_range": None,
    "dominant_hand_y_range": None,
    "dominant_hand_z_range": None,
    "not_dominant_hand_x_range": None,
    "not_dominant_hand_y_range": None,
    "not_dominant_hand_z_range": None,

    # Press features
    "dominant_hand_trigger_press_count": None,
    "not_dominant_hand_trigger_press_count": None,
    "dominant_hand_trigger_pressure_mean": None,
    "not_dominant_hand_trigger_pressure_mean": None,

    # Grip count features
    "dominant_hand_grip_count": None,
    "not_dominant_hand_grip_count": None,
    "dominant_hand_grip_mean": None,
    "not_dominant_hand_grip_mean": None,
}

In [291]:
dominant_hand = dominant_hand[1]
not_dominant_hand = 'Left' if dominant_hand == 'Right' else 'Right'
dominant_hand, not_dominant_hand

('Right', 'Left')

In [292]:
controller_dict["dominant_hand_total_distance"]     = du.calculate_total_hand_distance(df,dominant_hand)
controller_dict["not_dominant_hand_total_distance"] = du.calculate_total_hand_distance(df,not_dominant_hand)

In [293]:
controller_dict["dominant_hand_mean_speed"], controller_dict["dominant_hand_max_speed"]     = du.calculate_hand_dinstance_speed_metrics(df, dominant_hand)
controller_dict["not_dominant_hand_mean_speed"], controller_dict["not_dominant_hand_max_speed"] = du.calculate_hand_dinstance_speed_metrics(df, not_dominant_hand)

In [294]:
controller_dict['dominant_hand_x_range']   = round(df[f'{dominant_hand}Ctrl_X'].max() - df[f'{dominant_hand}Ctrl_X'].min(),2)
controller_dict['dominant_hand_y_range']   = round(df[f'{dominant_hand}Ctrl_Y'].max() - df[f'{dominant_hand}Ctrl_Y'].min(),2)
controller_dict['dominant_hand_z_range']   = round(df[f'{dominant_hand}Ctrl_Z'].max() - df[f'{dominant_hand}Ctrl_Z'].min(),2)

controller_dict['not_dominant_hand_x_range']  = round(df[f'{not_dominant_hand}Ctrl_X'].max() - df[f'{not_dominant_hand}Ctrl_X'].min(),2)
controller_dict['not_dominant_hand_y_range']  = round(df[f'{not_dominant_hand}Ctrl_Y'].max() - df[f'{not_dominant_hand}Ctrl_Y'].min(),2)
controller_dict['not_dominant_hand_z_range']  = round(df[f'{not_dominant_hand}Ctrl_Z'].max() - df[f'{not_dominant_hand}Ctrl_Z'].min(),2)

In [295]:
controller_dict["dominant_hand_trigger_press_count"], controller_dict["dominant_hand_trigger_pressure_mean"] = du.calculate_trigger_or_grip_hand_metrics(df, dominant_hand, 'Trigger')

controller_dict["not_dominant_hand_trigger_press_count"], controller_dict["not_dominant_hand_trigger_pressure_mean"] = du.calculate_trigger_or_grip_hand_metrics(df, not_dominant_hand, 'Trigger')

In [296]:
# Grip count features
controller_dict["dominant_hand_grip_count"], controller_dict["dominant_hand_grip_mean"] = du.calculate_trigger_or_grib_hand_metrics(df, dominant_hand, 'Grip')
controller_dict["not_dominant_hand_grip_count"], controller_dict["not_dominant_hand_grip_mean"]= du.calculate_trigger_or_grib_hand_metrics(df, not_dominant_hand, 'Grip')

In [297]:
controller_dict

{'dominant_hand_total_distance': np.float64(8.19),
 'not_dominant_hand_total_distance': np.float64(2.02),
 'dominant_hand_mean_speed': np.float64(0.17),
 'not_dominant_hand_mean_speed': np.float64(0.04),
 'dominant_hand_max_speed': np.float64(10.35),
 'not_dominant_hand_max_speed': np.float64(10.35),
 'dominant_hand_x_range': np.float64(0.43),
 'dominant_hand_y_range': np.float64(1.17),
 'dominant_hand_z_range': np.float64(0.46),
 'not_dominant_hand_x_range': np.float64(0.16),
 'not_dominant_hand_y_range': np.float64(1.19),
 'not_dominant_hand_z_range': np.float64(0.35),
 'dominant_hand_trigger_press_count': 7,
 'not_dominant_hand_trigger_press_count': 0,
 'dominant_hand_trigger_pressure_mean': np.float64(0.01),
 'not_dominant_hand_trigger_pressure_mean': np.float64(0.0),
 'dominant_hand_grip_count': 59,
 'not_dominant_hand_grip_count': 0,
 'dominant_hand_grip_mean': np.float64(0.12431447963800904),
 'not_dominant_hand_grip_mean': np.float64(0.0)}

## 4.3 Automatize filling out Phase-Level dictionary

In [ ]:
def creating_event_dictionary(df: pd.DataFrame, test_name: str, empy_dictionaries:list, phase_dict: dict) -> dict:

    # filling read_time dict
    reading_time_dict = du.filling_reading_time_dict(df, empy_dictionaries[0], phase_dict['phase_duration'])

    # filling hover_dict
    hover_dict = du.filling_hover_dict(df, empy_dictionaries[1], phase_dict['phase_duration'])

    # filling press_dict
    press_dict = du.filling_press_dict(df, empy_dictionaries[2], phase_dict['phase_duration'])

    # filling grab_dict
    grab_dict = du.filling_grab_dict(df, empy_dictionaries[3], phase_dict['phase_duration'])

    # filling gaze_dict
    gaze_dict = du.filling_gaze_dict(df, empy_dictionaries[4], phase_dict['phase_duration'])

    # filling behavior_dict
    behavior_dict = du.filling_behavior_dict(df, empy_dictionaries[5], hover_dict, press_dict, reading_time_dict, phase_dict['phase_duration'])

    # filling temporal_dict
    temporal_dict = du.filling_temporal_dict(df, empy_dictionaries[6])

    # concate all dictionaries
    event_dictionary = reading_time_dict | hover_dict | press_dict | grab_dict | gaze_dict | behavior_dict | temporal_dict
    match test_name:

        case 'Tutorial':
            return event_dictionary
        
        case 'ObjectRecognition':

            # extra features only for ObjectRecognition
            obj_recognition_dict = {
                "obj_recognition_score": None,
                "obj_recognition_mean_success_duration" : None,
                "obj_recognition_mean_choose_wrong_obj": None,
                "obj_recognition_total_duration": None
            }

            # fill and add extra features to basic dict
            obj_recognition_dict = du.filling_obj_recognition_dict()
            event_dictionary.update(obj_recognition_dict)

            return event_dictionary
        
        case 'Visuospatial':
            
            # extra features only for Visuospatial
            visuospatial_dict = {
                "visuospatial_score": None,
                "visuospatial_total_wrong_placement": None,
                "visuospatial_total_duration" : None
            }

            # fill and add extra features to basic dict
            visuospatial_dict = du.filling_visuospatial_dict(df, visuospatial_dict)
            event_dictionary.update(visuospatial_dict)
            
            return event_dictionary
        
        case 'Memory':

            # extra features only for memory_dict
            memory_dict = {
                "memory_score": None,
                "memory_delay_first_action": None,
                "memory_total_wrong_recall" : None,
                "memory_mean_recall": None,
                "memory_cognitive_freez_count": None,
                "memory_cognitive_freez_mean_duration": None,
                "memory_total_duration" : None
            }

            # fill and add extra features to basic dict
            memory_dict = du.filling_memory_dict(df, memory_dict)
            event_dictionary.update(memory_dict)
            
            return event_dictionary
        
        case _ :
            raise ValueError("not valid value for test_name!!!")