# 0. Library

In [43]:
import pandas as pd
from pathlib import Path
import re

import importlib
import sys
sys.path.append('../') 
from features import data_utils as du
from features import data_pipeline as dp
from features import general_func as gf
import constants_data as cd

# Reload
importlib.reload(du)
importlib.reload(dp)
importlib.reload(gf)
importlib.reload(cd)

# 1. Paths and Constants

In [47]:
# Constants and paths
parent_folder = Path("../..") # go 2 folder up= "../.."
df_path = parent_folder / "data" / "produced_csv" / "1.extracted_features.csv"
 
df = pd.read_csv(df_path)

df.head()

,Paitent_id,Age,Gender,dominant_hand,Sessions_Completed_out_of_4,Help_Rating_out_of_5,MoCA_Score,Tutorial_reading_time_happened,Tutorial_total_reading_time,Tutorial_mean_reading_time,...,Memory_not_dominant_hand_y_range,Memory_not_dominant_hand_z_range,Memory_dominant_hand_trigger_press_count,Memory_not_dominant_hand_trigger_press_count,Memory_dominant_hand_trigger_pressure_mean,Memory_not_dominant_hand_trigger_pressure_mean,Memory_dominant_hand_grip_count,Memory_not_dominant_hand_grip_count,Memory_dominant_hand_grip_mean,Memory_not_dominant_hand_grip_mean
0,P001,NaN,Female,Right,4,4,28.0,1,45.03,15.01,...,0.80,0.50,35,0,0.01,0.0,1275,0,0.40,0.0
1,P002,59.0,Female,Right,4,2,NaN,1,171.99,57.33,...,0.61,1.15,63,0,0.02,0.0,222,0,0.09,0.0
2,P003,82.0,Male,Right,4,1,26.0,1,338.75,112.92,...,0.75,0.61,12,0,0.00,0.0,277,0,0.09,0.0
3,P004,75.0,Male,Left,4,2,NaN,1,114.78,38.26,...,0.59,0.92,47,1,0.03,0.0,157,0,0.10,0.0
4,P005,62.0,Male,Right,4,1,27.0,1,152.90,50.97,...,0.58,0.48,28,0,0.02,0.0,125,0,0.08,0.0

In [53]:
df_cleaning = df.copy() # copy original

# 2. Data preprocessing

## 2.1 Creating target column

In [33]:
df_cleaning['MoCA_Score']

0     28.0
1      NaN
2     26.0
3      NaN
4     27.0
5     27.0
6     26.0
7     29.0
8      NaN
9     25.0
10    28.0
11    29.0
12     NaN
13    17.0
14    30.0
15     NaN
16     NaN
17    27.0
18     NaN
19    29.0
20     NaN
21     NaN
22     NaN
23     NaN
24     NaN
25     NaN
26     NaN
27     NaN
28     NaN
29     NaN
30     NaN
31     NaN
32     NaN
33     NaN
34     NaN
35     NaN
36     NaN
37     NaN
38     NaN
39     NaN
Name: MoCA_Score, dtype: float64

In [34]:
df_cleaning.loc[20:,'MoCA_Score'] = 26

In [35]:
df_cleaning.loc[20:,'MoCA_Score']

20    26.0
21    26.0
22    26.0
23    26.0
24    26.0
25    26.0
26    26.0
27    26.0
28    26.0
29    26.0
30    26.0
31    26.0
32    26.0
33    26.0
34    26.0
35    26.0
36    26.0
37    26.0
38    26.0
39    26.0
Name: MoCA_Score, dtype: float64

In [36]:
median_score = df_cleaning['MoCA_Score'].median()
df_cleaning['MoCA_Score'] = df_cleaning['MoCA_Score'].fillna(median_score)

In [37]:
df_cleaning['MoCA_Score']

0     28.0
1     26.0
2     26.0
3     26.0
4     27.0
5     27.0
6     26.0
7     29.0
8     26.0
9     25.0
10    28.0
11    29.0
12    26.0
13    17.0
14    30.0
15    26.0
16    26.0
17    27.0
18    26.0
19    29.0
20    26.0
21    26.0
22    26.0
23    26.0
24    26.0
25    26.0
26    26.0
27    26.0
28    26.0
29    26.0
30    26.0
31    26.0
32    26.0
33    26.0
34    26.0
35    26.0
36    26.0
37    26.0
38    26.0
39    26.0
Name: MoCA_Score, dtype: float64

In [54]:
df_cleaning['Target'] = df_cleaning['MoCA_Score'].apply(du.severity_level_MoCA)
df_cleaning['Target']

SystemExit: Unkown Error!!!

/home/smira/myproject/detection_AD_with_VR_data/venv/lib/python3.14/site-packages/IPython/core/interactiveshell.py:3756: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [49]:
df_cleaning = df_cleaning.drop(columns=['MoCA_Score'])

In [52]:
df_cleaning['Target']

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
Name: Target, dtype: int64

In [51]:
df_cleaning = dp.create_target_column(df_cleaning)

In [ ]:
df_cleaning = dp.check_Nan_values(original_df= df_cleaning, missing_values_threshold=0.6, target_col='MoCA_Score')

Missing values found, number of columns with Nan values : 5
{'Age': 1, 'MoCA_Score': 27, 'Tutorial_std_duration_gaze': 1, 'ObjectRecognition_std_duration_gaze': 12, 'Memory_cognitive_freez_mean_duration': 37}
Removed columns :['Memory_cognitive_freez_mean_duration']
All Nan values are handled successfuly.

In [ ]:
df_cleaning = dp.check_columns_type(df_without_Nan= df_cleaning)

Columns before one hot encoding :

          Total columns :376,
          Numerical columns : 373,
          Categorical columns : 3,
          Unkown columns : 0


 Columns after one hot encoding :

          Total columns :375,
          Numerical columns : 375,
          Categorical columns : 0,
          Unkown columns : 0

All Categorical columns are encoded successfuly.

In [ ]:
df_cleaning = dp.check_constant_column(df_without_categorical_column=df_cleaning)

Columns before removing constant columns : 375
There are 28 constant columns, removing them...

 Columns after removing constant columns : 347
All constant columns are removed successfuly.

In [ ]:
df_cleaning = dp.check_correlation(df_cleaning)

Number of columns before removing 347
No Nan correlation.
Number of small correlation 162
Number of redundant features 65
Number of total useless columns 227, Removing them...
All useless correlations are removed successfully.
Number of columns after removing 120

In [ ]:
df_cleaning.head(50)

,Age,Help_Rating_out_of_5,MoCA_Score,Tutorial_total_reading_time,Tutorial_max_reading_time,Tutorial_intensity_reading_time,Tutorial_total_duration_hover,Tutorial_mean_duration_hover,Tutorial_max_duration_hover,Tutorial_std_duration_hover,...,Memory_Yaw_std,Memory_Pitch_std,Memory_Roll_std,Memory_Yaw_range,Memory_dominant_hand_mean_speed,Memory_not_dominant_hand_mean_speed,Memory_dominant_hand_z_range,Memory_not_dominant_hand_y_range,Gender_Male,dominant_hand_Right
0,73.0,4,28.0,45.03,21.00,0.92,20.64,1.03,2.29,0.74,...,26.23,161.72,177.36,99.05,0.16,0.03,0.82,0.80,0,1
1,59.0,2,27.0,171.99,91.56,0.98,53.05,1.02,13.42,2.25,...,47.08,165.33,172.85,180.39,0.06,0.04,1.02,0.61,0,1
2,82.0,1,26.0,338.75,155.14,0.99,145.79,2.11,20.01,4.20,...,23.27,161.90,162.61,109.38,0.06,0.01,0.98,0.75,1,1
3,75.0,2,27.0,114.78,68.19,0.97,46.90,1.47,13.24,2.97,...,25.75,171.61,101.97,234.99,0.06,0.03,0.50,0.59,1,0
4,62.0,1,27.0,152.90,88.47,0.97,54.33,1.81,11.62,2.66,...,30.07,170.64,169.17,248.93,0.12,0.02,1.05,0.58,1,1
5,78.0,2,27.0,181.69,90.17,0.98,91.62,2.78,23.45,5.15,...,31.96,136.51,170.83,174.64,0.12,0.02,0.82,0.42,0,1
6,71.0,2,26.0,190.51,83.86,0.98,102.68,2.57,21.86,4.70,...,27.48,169.32,125.66,146.78,0.11,0.03,0.82,0.64,0,1
7,69.0,1,29.0,208.51,99.78,0.98,111.97,3.73,28.11,7.31,...,23.40,152.95,177.44,103.96,0.07,0.03,0.67,0.33,0,1
8,73.0,3,27.0,198.53,94.27,0.98,101.63,1.95,28.93,4.62,...,36.69,156.72,144.17,150.56,0.10,0.01,1.22,0.59,1,1
9,81.0,2,25.0,265.83,115.47,0.99,100.31,3.34,18.00,4.84,...,31.91,164.07,134.91,356.32,0.13,0.01,1.17,0.63,0,1
10,74.0,2,28.0,210.34,79.48,0.98,54.97,1.90,11.14,2.98,...,39.61,149.60,166.47,351.12,0.16,0.01,0.93,0.33,0,1
11,65.0,2,29.0,164.28,60.26,0.98,60.21,2.32,13.10,3.74,...,72.50,160.03,153.53,357.26,0.15,0.02,1.07,0.46,1,1
12,61.0,2,27.0,109.99,62.12,0.96,84.66,1.88,16.62,4.20,...,39.32,166.38,160.45,347.03,0.11,0.01,0.70,0.41,0,1
13,79.0,4,17.0,534.07,206.77,0.99,154.15,2.96,40.76,7.92,...,31.27,170.65,78.32,289.87,0.09,0.01,1.26,0.79,1,0
14,74.0,2,30.0,269.98,180.21,0.99,55.43,1.91,12.04,2.88,...,31.48,167.40,97.98,104.98,0.19,0.04,1.33,0.38,0,1
15,75.0,2,27.0,260.47,122.55,0.98,96.61,1.73,13.08,2.76,...,30.31,167.10,174.40,111.84,0.11,0.01,0.95,0.47,0,1
16,76.0,2,27.0,241.54,184.65,0.98,50.29,3.35,12.99,4.39,...,37.38,163.36,99.45,228.45,0.10,0.03,0.95,0.49,0,1
17,69.0,2,27.0,371.73,194.47,0.99,163.49,2.77,28.71,5.83,...,42.58,151.28,140.12,158.68,0.10,0.04,0.91,0.70,0,1
18,70.0,2,27.0,279.39,178.58,0.99,64.94,1.16,16.35,3.03,...,47.70,143.47,55.44,144.81,0.11,0.05,1.19,0.54,1,1
19,72.0,2,29.0,201.54,95.63,0.98,85.19,1.85,24.97,4.02,...,45.44,163.94,122.14,162.57,0.10,0.02,0.81,0.41,0,1

In [ ]:
# save df
parent_folder = Path("../..") # go 2 folder up= "../.."
df_path = parent_folder / "data" / "produced_csv"
name = "2.cleaned_features_20_patients.csv"
df_cleaning.to_csv(df_path / name, index=False)