# 0.Library

In [16]:
# general
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import importlib
import joblib

# ML
from sklearn.model_selection import LeaveOneOut, cross_validate

# MLFlow
import mlflow

# Paths
import sys
sys.path.append('../') 
from features import data_utils as du
from features import data_pipeline as dp
from features import general_func as gf
import constants_data as cd
from features import model_utils as mu

# Reload
importlib.reload(du)
importlib.reload(dp)
importlib.reload(gf)
importlib.reload(cd)
importlib.reload(mu)

# 1. Paths and Constants

In [6]:
parent_folder = Path("../..") # go 2 folder up= "../.."

# Read models path
models_paths_folder = parent_folder / "models" / "solution_one"
best_model = "SelectKBest_SVR_20.pkl"

# Read dataframe input (test set)
df_path = parent_folder / "data" / "produced_csv" / "2.cleaned_features_13_patients.csv"
df      = pd.read_csv(df_path)
df.head()

X = df.drop(columns=['MoCA_Score'])

# 2. Predict MoCA score by best model

In [7]:
# Read the best model
path_best_model = models_paths_folder / best_model
loaded_model = joblib.load(path_best_model)

In [8]:
y_pred = loaded_model.predict(X)

In [9]:
y_pred

array([27.89979686, 26.26152295, 27.24930112, 27.09973687, 26.69299299,
       28.49428109, 26.28595373, 27.89979683, 28.0461207 , 25.93394207,
       27.87094211, 26.9006694 , 28.34560273])

In [10]:
df['Predicted_MoCA'] = y_pred
df.head()

,Age,Help_Rating_out_of_5,MoCA_Score,Tutorial_total_reading_time,Tutorial_intensity_reading_time,Tutorial_total_count_hover,Tutorial_total_duration_hover,Tutorial_mean_duration_hover,Tutorial_max_duration_hover,Tutorial_total_count_press,...,Memory_Pitch_std,Memory_Roll_std,Memory_Yaw_range,Memory_Roll_range,Memory_dominant_hand_mean_speed,Memory_not_dominant_hand_mean_speed,Memory_dominant_hand_z_range,Memory_not_dominant_hand_y_range,Gender_Male,Predicted_MoCA
0,73.0,4,28.0,45.03,0.92,32,20.64,1.03,2.29,8,...,161.72,177.36,99.05,360.00,0.16,0.03,0.82,0.80,0,27.899797
1,82.0,1,26.0,338.75,0.99,688,145.79,2.11,20.01,9,...,161.90,162.61,109.38,359.99,0.06,0.01,0.98,0.75,1,26.261523
2,62.0,1,27.0,152.90,0.97,61,54.33,1.81,11.62,8,...,170.64,169.17,248.93,359.98,0.12,0.02,1.05,0.58,1,27.249301
3,78.0,2,27.0,181.69,0.98,26,91.62,2.78,23.45,9,...,136.51,170.83,174.64,359.98,0.12,0.02,0.82,0.42,0,27.099737
4,71.0,2,26.0,190.51,0.98,109,102.68,2.57,21.86,8,...,169.32,125.66,146.78,359.99,0.11,0.03,0.82,0.64,0,26.692993

In [11]:
df[['MoCA_Score','Predicted_MoCA']]

    MoCA_Score  Predicted_MoCA
0         28.0       27.899797
1         26.0       26.261523
2         27.0       27.249301
3         27.0       27.099737
4         26.0       26.692993
5         29.0       28.494281
6         25.0       26.285954
7         28.0       27.899797
8         29.0       28.046121
9         17.0       25.933942
10        30.0       27.870942
11        27.0       26.900669
12        29.0       28.345603

In [18]:

df['severity_level'] = df['MoCA_Score'].apply(du.severity_level_MoCA)
df['predicted_severity_level'] = df['Predicted_MoCA'].apply(du.severity_level_MoCA)

In [19]:
df[['MoCA_Score','severity_level','predicted_severity_level','Predicted_MoCA']]

    MoCA_Score       severity_level predicted_severity_level  Predicted_MoCA
0         28.0               Normal                   Normal       27.899797
1         26.0               Normal                   Normal       26.261523
2         27.0               Normal                   Normal       27.249301
3         27.0               Normal                   Normal       27.099737
4         26.0               Normal                   Normal       26.692993
5         29.0               Normal                   Normal       28.494281
6         25.0      Mild impairment                   Normal       26.285954
7         28.0               Normal                   Normal       27.899797
8         29.0               Normal                   Normal       28.046121
9         17.0  Moderate impairment          Mild impairment       25.933942
10        30.0               Normal                   Normal       27.870942
11        27.0               Normal                   Normal       26.900669
12        29.0               Normal                   Normal       28.345603

In [20]:
name = f"5.cleaned_features_13_young_patients_with_predicted_target.csv"

# save df
parent_folder = Path("../..") # go 2 folder up= "../.."
df_path = parent_folder / "data" / "produced_csv"
df.to_csv(df_path / name, index=False)