# 0. Library

In [45]:
import pandas as pd
import re

# 1. Preprocess data

In [53]:
tutorial_events     = pd.read_csv('../../data/PatientsData/p001_20260502_113117/20260502_113117_01_Tutorial_events.csv', sep=",", on_bad_lines="skip")
tutorial_trajectory = pd.read_csv('../../data/PatientsData/p001_20260502_113117/20260502_113117_01_Tutorial_trajectory.csv', sep=",", on_bad_lines="skip")

In [60]:
file_path = '../../data/PatientsData/p001_20260502_113117/20260502_113117_01_Tutorial_events.csv'

In [73]:
with open(file_path, "r", encoding="utf-8") as f:
    # read all lines from the file
    lines = f.readlines()

# extract the first line (header) and split it into columns
columns_line = lines[0]
columns = columns_line.strip().split(",")
lines.pop(0)  # remove the header line from the list of lines
print(columns)

# separate lines based on the section break
pattern = r"^--- SECTION BREAK:"
selected_lines = []

for line in lines:
    if re.match(pattern, line):
        #df = pd.DataFrame(selected_lines, columns=columns)
        break
    selected_lines.append(line)

print(selected_lines)

['Timestamp', 'PhaseTime_s', 'Section', 'EventType', 'ObjectName', 'Hand', 'IsCorrect', 'Duration_s', 'Distance_m', 'Details']
['2026-05-02 11:31:17.628,0.000,Default,PHASE_START,,,,0.000,0.000,Phase=01_Tutorial,Section=Default,SessionID=20260502_113117,PatientID=,SampleRate=10Hz,Device=Oculus Quest 3,GazeTrackerActive=True\n', '2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,,,0.000,0.000,Section=Default,Panel=WelcomePanel\n', '2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=1\n', '2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.95s\n', '2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=2\n', '2026-05-02 11:31:26.183,3.217,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.11s\n', '2026-05-02 11:31:26.378,3.411,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=3\n', '2026-05-02 11:31:26.697,3.731,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.32s\n', '2026-05-02 11:31:28.907,5.940,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=4\n', '2026-05-02 11:31:29.448,6.483,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.54s\n', '2026-05-02 11:31:35.603,12.637,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=5\n', '2026-05-02 11:31:37.895,14.930,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=2.29s\n', '2026-05-02 11:31:38.423,15.457,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=6\n', '2026-05-02 11:31:38.909,15.943,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.49s\n', '2026-05-02 11:31:39.381,16.415,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=7\n', '2026-05-02 11:31:39.979,17.013,Default,BUTTON_PRESSED,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],PressTime=0.60s\n', '2026-05-02 11:31:40.200,17.235,Default,BUTTON_RELEASED,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],PressDuration=0.222s\n', '2026-05-02 11:31:40.205,17.235,Default,PANEL_DISMISSED,WelcomePanel,,,17.235,0.000,Section=Default,Panel=WelcomePanel,ReadingTime=17.23s\n', '2026-05-02 11:31:40.206,17.235,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.82s\n', '2026-05-02 11:31:40.208,17.235,Default,SECTION_END,,,,17.235,0.000,Section=Default,Duration=17.23s\n']

In [49]:
type(lines)

list

In [74]:
selected_lines

['2026-05-02 11:31:17.628,0.000,Default,PHASE_START,,,,0.000,0.000,Phase=01_Tutorial,Section=Default,SessionID=20260502_113117,PatientID=,SampleRate=10Hz,Device=Oculus Quest 3,GazeTrackerActive=True\n',
 '2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,,,0.000,0.000,Section=Default,Panel=WelcomePanel\n',
 '2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=1\n',
 '2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.95s\n',
 '2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=2\n',
 '2026-05-02 11:31:26.183,3.217,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.11s\n',
 '2026-05-02 11:31:26.378,3.411,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=3\n',
 '2026-05-02 11:31:26.697,3.731,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.32s\n',
 '2026-05-02 11:31:28.907,5.940,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=4\n',
 '2026-05-02 11:31:29.448,6.483,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.54s\n',
 '2026-05-02 11:31:35.603,12.637,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=5\n',
 '2026-05-02 11:31:37.895,14.930,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=2.29s\n',
 '2026-05-02 11:31:38.423,15.457,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=6\n',
 '2026-05-02 11:31:38.909,15.943,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.49s\n',
 '2026-05-02 11:31:39.381,16.415,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=7\n',
 '2026-05-02 11:31:39.979,17.013,Default,BUTTON_PRESSED,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],PressTime=0.60s\n',
 '2026-05-02 11:31:40.200,17.235,Default,BUTTON_RELEASED,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],PressDuration=0.222s\n',
 '2026-05-02 11:31:40.205,17.235,Default,PANEL_DISMISSED,WelcomePanel,,,17.235,0.000,Section=Default,Panel=WelcomePanel,ReadingTime=17.23s\n',
 '2026-05-02 11:31:40.206,17.235,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.82s\n',
 '2026-05-02 11:31:40.208,17.235,Default,SECTION_END,,,,17.235,0.000,Section=Default,Duration=17.23s\n']

In [77]:
cleaned_selected_lines = []
for line in selected_lines:
    messy_row = line.strip().split(",")
    messy_row[10] = messy_row[10:]
    del messy_row[10:]
    cleaned_selected_lines.append(messy_row)

In [78]:
cleaned_selected_lines

[['2026-05-02 11:31:17.628',
  '0.000',
  'Default',
  'PHASE_START',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Phase=01_Tutorial'],
 ['2026-05-02 11:31:17.630',
  '0.000',
  'Default',
  'PANEL_SHOWN',
  'WelcomePanel',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:22.971',
  '0.000',
  'Default',
  'BUTTON_HOVER_START',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:23.918',
  '0.952',
  'Default',
  'BUTTON_HOVER_END',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:26.072',
  '3.106',
  'Default',
  'BUTTON_HOVER_START',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:26.183',
  '3.217',
  'Default',
  'BUTTON_HOVER_END',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:26.378',
  '3.411',
  'Default',
  'BUTTON_HOVER_START',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:26.697',
  '3.731',
  'Default',
  'BUTTON_HOVER_END',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:28.907',
  '5.940',
  'Default',
  'BUTTON_HOVER_START',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:29.448',
  '6.483',
  'Default',
  'BUTTON_HOVER_END',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:35.603',
  '12.637',
  'Default',
  'BUTTON_HOVER_START',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:37.895',
  '14.930',
  'Default',
  'BUTTON_HOVER_END',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:38.423',
  '15.457',
  'Default',
  'BUTTON_HOVER_START',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:38.909',
  '15.943',
  'Default',
  'BUTTON_HOVER_END',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:39.381',
  '16.415',
  'Default',
  'BUTTON_HOVER_START',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:39.979',
  '17.013',
  'Default',
  'BUTTON_PRESSED',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:40.200',
  '17.235',
  'Default',
  'BUTTON_RELEASED',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:40.205',
  '17.235',
  'Default',
  'PANEL_DISMISSED',
  'WelcomePanel',
  '',
  '',
  '17.235',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:40.206',
  '17.235',
  'Default',
  'BUTTON_HOVER_END',
  '',
  '',
  '',
  '0.000',
  '0.000',
  'Section=Default'],
 ['2026-05-02 11:31:40.208',
  '17.235',
  'Default',
  'SECTION_END',
  '',
  '',
  '',
  '17.235',
  '0.000',
  'Section=Default']]

In [63]:
x = selected_lines[0].strip().split(",")
x

['2026-05-02 11:31:17.628',
 '0.000',
 'Default',
 'PHASE_START',
 '',
 '',
 '',
 '0.000',
 '0.000',
 'Phase=01_Tutorial',
 'Section=Default',
 'SessionID=20260502_113117',
 'PatientID=',
 'SampleRate=10Hz',
 'Device=Oculus Quest 3',
 'GazeTrackerActive=True']

In [67]:
x[10] = x[10:]

In [68]:
x[10]

['Section=Default',
 'SessionID=20260502_113117',
 'PatientID=',
 'SampleRate=10Hz',
 'Device=Oculus Quest 3',
 'GazeTrackerActive=True']

In [30]:
tutorial_events.columns

Index(['Timestamp', 'PhaseTime_s', 'Section', 'EventType', 'ObjectName',
       'Hand', 'IsCorrect', 'Duration_s', 'Distance_m', 'Details'],
      dtype='object')

In [31]:
tutorial_events.shape

(81, 10)

In [32]:
tutorial_events.head()

,,,,,,Timestamp,PhaseTime_s,Section,EventType,ObjectName,Hand,IsCorrect,Duration_s,Distance_m,Details
2026-05-02 11:31:17.628,0.000,Default,PHASE_START,NaN,NaN,NaN,0.0,0.0,Phase=01_Tutorial,Section=Default,SessionID=20260502_113117,PatientID=,SampleRate=10Hz,Device=Oculus Quest 3,GazeTrackerActive=True
2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,NaN,NaN,0.0,0.0,Section=Default,Panel=WelcomePanel,NaN,NaN,NaN,NaN,NaN
2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=1,NaN,NaN,NaN,NaN
2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.95s,NaN,NaN,NaN,NaN
2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=2,NaN,NaN,NaN,NaN

In [33]:
separator_indices = tutorial_events.index[tutorial_events.iloc[:,0] == "--- SECTION BREAK: ButtonSelection ---,,,,,,,"].tolist()

In [34]:
separator_indices

[]

In [22]:
tutorial_events.iloc[22,:]

Timestamp                               NaN
PhaseTime_s                             0.0
Section                                 0.0
EventType           Section=ButtonSelection
ObjectName     Panel=ButtonInstructionPanel
Hand                                    NaN
IsCorrect                               NaN
Duration_s                              NaN
Distance_m                              NaN
Details                                 NaN
Name: (2026-05-02 11:31:40.209, 17.235, ButtonSelection, PANEL_SHOWN, ButtonInstructionPanel, nan), dtype: object

In [11]:
rows = tutorial_events[tutorial_events.iloc[:, :] == "--- SECTION BREAK"]

In [12]:
rows

                                                                                        Timestamp  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN       NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN       NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN       NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN       NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN       NaN
...                                                                                           ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN       NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN       NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN       NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN       NaN
                                                    PHASE_END          NaN          NaN       NaN

                                                                                         PhaseTime_s  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN          NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN          NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN          NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN          NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN          NaN
...                                                                                              ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN          NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN          NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN          NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN          NaN
                                                    PHASE_END          NaN          NaN          NaN

                                                                                         Section  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN      NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN      NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN      NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN      NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN      NaN
...                                                                                          ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN      NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN      NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN      NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN      NaN
                                                    PHASE_END          NaN          NaN      NaN

                                                                                        EventType  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN       NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN       NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN       NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN       NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN       NaN
...                                                                                           ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN       NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN       NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN       NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN       NaN
                                                    PHASE_END          NaN          NaN       NaN

                                                                                        ObjectName  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN        NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN        NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN        NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN        NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN        NaN
...                                                                                            ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN        NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN        NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN        NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN        NaN
                                                    PHASE_END          NaN          NaN        NaN

                                                                                        Hand  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN  NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN  NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN  NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN  NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN  NaN
...                                                                                      ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN  NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN  NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN  NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN  NaN
                                                    PHASE_END          NaN          NaN  NaN

                                                                                        IsCorrect  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN       NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN       NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN       NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN       NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN       NaN
...                                                                                           ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN       NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN       NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN       NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN       NaN
                                                    PHASE_END          NaN          NaN       NaN

                                                                                        Duration_s  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN        NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN        NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN        NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN        NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN        NaN
...                                                                                            ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN        NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN        NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN        NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN        NaN
                                                    PHASE_END          NaN          NaN        NaN

                                                                                        Distance_m  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN        NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN        NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN        NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN        NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN        NaN
...                                                                                            ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN        NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN        NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN        NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN        NaN
                                                    PHASE_END          NaN          NaN        NaN

                                                                                        Details
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN     NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN     NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN     NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN     NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN     NaN
...                                                                                         ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN     NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN     NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN     NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN     NaN
                                                    PHASE_END          NaN          NaN     NaN

[81 rows x 10 columns]

In [8]:
import pandas as pd

# Read the CSV
#df = pd.read_csv("input.csv", header=None)
df = tutorial_events.copy()  # Using the tutorial_events DataFrame for demonstration
# Find rows containing the separator
separator = "--- SECTION BREAK"

# Create groups based on separator occurrences
groups = (df[0] == separator).cumsum()

# Remove separator rows
df_clean = df[df[0] != separator]

# Split and save
for i, (_, group) in enumerate(df_clean.groupby(groups[df_clean.index]), start=1):
    output_file = f"output_{i}.csv"
    group.to_csv(output_file, index=False, header=False)

    print(f"Created: {output_file}")

KeyError: 0

In [ ]:
# break the csv file into smaller files
separator = "--- SECTION BREAK"