# 0. Library

In [41]:
import pandas as pd
import re

import sys
sys.path.append('../') # these two lines allow the notebook to find the path to the source code contained in 'src'
from features.data_utils import creating_sections_of_csv

# 1. Preprocess data

In [2]:
tutorial_events     = pd.read_csv('../../data/PatientsData/p001_20260502_113117/20260502_113117_01_Tutorial_events.csv', sep=",", on_bad_lines="skip")
tutorial_trajectory = pd.read_csv('../../data/PatientsData/p001_20260502_113117/20260502_113117_01_Tutorial_trajectory.csv', sep=",", on_bad_lines="skip")

In [42]:
creating_sections_of_csv(file_path, "dd")

In [24]:
file_path = '../../data/PatientsData/p001_20260502_113117/20260502_113117_01_Tutorial_events.csv'
file_path_data_log = '../../data/patients_data_log.json'
df_data_log = pd.read_json(file_path_data_log)

In [25]:
df_data_log

,PatientID,Age,Gender,Start_Time,End_Time,Sessions_Completed_out_of_4,Help_Rating_out_of_5,MoCA_Score_or_Completed,VR_Unit
0,P001,None,Female,2026-05-22 11:31:00,2026-05-22 11:38:00,4,1,None,4
1,P002,59,Female,2026-05-22 12:05:00,2026-05-22 12:12:00,4,3,None,4
2,P003,82,Male,2026-05-22 12:50:00,2026-05-22 13:00:00,4,4,None,4
3,P004,75,Male,2026-05-22 13:07:00,2026-05-22 13:15:00,4,3,None,4
4,P005,62,Male,2026-05-22 13:25:00,2026-05-22 13:31:00,4,4,None,4
5,P006,78,Female,2026-05-22 13:35:00,2026-05-22 13:43:00,4,3,None,4
6,P007,71,Female,2026-05-22 13:45:00,2026-05-22 13:52:00,4,3,None,4
7,P008,69,Female,2026-05-22 14:00:00,2026-05-22 14:08:00,4,4,None,4
8,P009,73,Male,2026-05-22 14:20:00,2026-05-22 14:32:00,4,2,None,2
9,P010,81,Female,2026-05-22 14:43:00,2026-05-22 14:53:00,4,3,None,2
10,P011,74,Female,2026-05-22 14:54:00,2026-05-22 15:02:00,4,3,None,2
11,P012,65,Male,2026-05-22 15:05:00,2026-05-22 15:12:00,4,3,None,2
12,P013,61,Female,2026-05-22 15:13:00,2026-05-22 15:18:00,4,3,None,2
13,P014,79,Male,2026-05-22 15:24:00,2026-05-22 15:45:00,4,1,None,4
14,P015,74,Female,2026-05-22 15:47:00,2026-05-22 15:57:00,4,3,None,4
15,P016,75,Female,2026-05-22 15:59:00,2026-05-22 16:08:00,4,3,None,4
16,P017,76,Female,2026-05-22 16:09:00,2026-05-22 16:18:00,4,3,None,4
17,P018,69,Female,2026-05-22 16:18:00,2026-05-22 16:30:00,4,3,None,4
18,P019,70,Male,2026-05-22 16:31:00,2026-05-22 16:40:00,4,3,None,4
19,P020,72,Female,2026-05-22 16:41:00,2026-05-22 16:50:00,4,3,None,4

In [43]:
lines

['2026-05-02 11:31:17.628,0.000,Default,PHASE_START,,,,0.000,0.000,Phase=01_Tutorial,Section=Default,SessionID=20260502_113117,PatientID=,SampleRate=10Hz,Device=Oculus Quest 3,GazeTrackerActive=True\n',
 '2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,,,0.000,0.000,Section=Default,Panel=WelcomePanel\n',
 '2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=1\n',
 '2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.95s\n',
 '2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=2\n',
 '2026-05-02 11:31:26.183,3.217,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.11s\n',
 '2026-05-02 11:31:26.378,3.411,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=3\n',
 '2026-05-02 11:31:26.697,3.731,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.32s\n',
 '2026-05-02 11:31:28.907,5.940,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=4\n',
 '2026-05-02 11:31:29.448,6.483,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.54s\n',
 '2026-05-02 11:31:35.603,12.637,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=5\n',
 '2026-05-02 11:31:37.895,14.930,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=2.29s\n',
 '2026-05-02 11:31:38.423,15.457,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=6\n',
 '2026-05-02 11:31:38.909,15.943,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.49s\n',
 '2026-05-02 11:31:39.381,16.415,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=7\n',
 '2026-05-02 11:31:39.979,17.013,Default,BUTTON_PRESSED,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],PressTime=0.60s\n',
 '2026-05-02 11:31:40.200,17.235,Default,BUTTON_RELEASED,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],PressDuration=0.222s\n',
 '2026-05-02 11:31:40.205,17.235,Default,PANEL_DISMISSED,WelcomePanel,,,17.235,0.000,Section=Default,Panel=WelcomePanel,ReadingTime=17.23s\n',
 '2026-05-02 11:31:40.206,17.235,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.82s\n',
 '2026-05-02 11:31:40.208,17.235,Default,SECTION_END,,,,17.235,0.000,Section=Default,Duration=17.23s\n',
 '--- SECTION BREAK: ButtonSelection ---,,,,,,,\n',
 '2026-05-02 11:31:40.208,17.235,ButtonSelection,SECTION_START,,,,0.000,0.000,Section=ButtonSelection,PhaseTime=17.23s\n',
 '2026-05-02 11:31:40.209,17.235,ButtonSelection,PANEL_SHOWN,ButtonInstructionPanel,,,0.000,0.000,Section=ButtonSelection,Panel=ButtonInstructionPanel\n',
 '2026-05-02 11:31:40.209,17.235,ButtonSelection,BUTTON_CLICKED,,,,0.000,0.000,Section=ButtonSelection,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.82s,TotalHovers=7\n',
 '2026-05-02 11:31:44.409,21.443,ButtonSelection,BUTTON_HOVER_START,,,,0.000,0.000,Section=ButtonSelection,Button=PracticeButton1[TutorialButtonSelection],HoverCount=1\n',
 '2026-05-02 11:31:45.506,22.540,ButtonSelection,BUTTON_PRESSED,,,,0.000,0.000,Section=ButtonSelection,Button=PracticeButton1[TutorialButtonSelection],PressTime=1.10s\n',
 '2026-05-02 11:31:45.659,22.693,ButtonSelection,BUTTON_RELEASED,,,,0.000,0.000,Section=ButtonSelection,Button=PracticeButton1[TutorialButtonSelection],PressDuration=0.153s\n',
 '2026-05-02 11:31:45.660,22.693,ButtonSelection,BUTTON_PRESSED,,,,0.000,0.000,Section=ButtonSelection,Button=1,PressCount=1\n',
 '2026-05-02 11:31:45.661,22.693,ButtonSelection,BUTTON_CLICKED,,,,0.000,0.000,Section=ButtonSelection,Button=PracticeButton1[TutorialButtonSelection],HoverDuration=1.25s,TotalHovers=1\n',
 '2026-05-02 11:31:45.923,22.956,ButtonSelection,BUTTON_HOVER_END,,,,0.000,0.000,Section=ButtonSelection,Button=PracticeButton1[TutorialButtonSelection],HoverDuration=1.51s\n',
 '2026-05-02 11:31:46.130,23.165,ButtonSelection,BUTTON_HOVER_START,,,,0.000,0.000,Section=ButtonSelection,Button=PracticeButton2[TutorialButtonSelection],HoverCount=1\n',
 '2026-05-02 11:31:46.881,23.915,ButtonSelection,BUTTON_PRESSED,,,,0.000,0.000,Section=ButtonSelection,Button=PracticeButton2[TutorialButtonSelection],PressTime=0.75s\n',
 '2026-05-02 11:31:47.006,24.040,ButtonSelection,BUTTON_RELEASED,,,,0.000,0.000,Section=ButtonSelection,Button=PracticeButton2[TutorialButtonSelection],PressDuration=0.124s\n',
 '2026-05-02 11:31:47.008,24.040,ButtonSelection,BUTTON_PRESSED,,,,0.000,0.000,Section=ButtonSelection,Button=2,PressCount=2\n',
 '2026-05-02 11:31:47.008,24.040,ButtonSelection,PANEL_DISMISSED,ButtonInstructionPanel,,,6.805,0.000,Section=ButtonSelection,Panel=ButtonInstructionPanel,ReadingTime=6.80s\n',
 '2026-05-02 11:31:47.008,24.040,ButtonSelection,BUTTON_SECTION_COMPLETE,,,,0.000,0.000,Section=ButtonSelection,CompletionTime=6.80s\n',
 '2026-05-02 11:31:47.009,24.040,ButtonSelection,BUTTON_CLICKED,,,,0.000,0.000,Section=ButtonSelection,Button=PracticeButton2[TutorialButtonSelection],HoverDuration=0.87s,TotalHovers=1\n',
 '2026-05-02 11:31:47.242,24.276,ButtonSelection,BUTTON_HOVER_END,,,,0.000,0.000,Section=ButtonSelection,Button=PracticeButton2[TutorialButtonSelection],HoverDuration=1.11s\n',
 '2026-05-02 11:31:47.297,24.331,ButtonSelection,BUTTON_HOVER_START,,,,0.000,0.000,Section=ButtonSelection,Button=PracticeButton2[TutorialButtonSelection],HoverCount=2\n',
 '2026-05-02 11:31:47.381,24.415,ButtonSelection,BUTTON_HOVER_END,,,,0.000,0.000,Section=ButtonSelection,Button=PracticeButton2[TutorialButtonSelection],HoverDuration=0.08s\n',
 '2026-05-02 11:31:48.008,25.040,ButtonSelection,SECTION_END,,,,7.805,0.000,Section=ButtonSelection,Duration=7.80s\n',
 '--- SECTION BREAK: GrabPractice ---,,,,,,,\n',
 '2026-05-02 11:31:48.008,25.040,GrabPractice,SECTION_START,,,,0.000,0.000,Section=GrabPractice,PhaseTime=25.04s\n',
 '2026-05-02 11:31:48.009,25.040,GrabPractice,PANEL_SHOWN,GrabInstructionPanel,,,0.000,0.000,Section=GrabPractice,Panel=GrabInstructionPanel\n',
 '2026-05-02 11:31:48.023,25.061,GrabPractice,HOVER_START,Cube,,FALSE,0.000,0.000,Section=GrabPractice,IsCorrect=False\n',
 '2026-05-02 11:31:48.046,25.080,GrabPractice,HOVER_END,Cube,,FALSE,0.019,0.000,Section=GrabPractice,HoverDuration=0.019s\n',
 '2026-05-02 11:31:48.073,25.107,GrabPractice,HOVER_START,Cube,,FALSE,0.000,0.000,Section=GrabPractice,IsCorrect=False\n',
 '2026-05-02 11:31:49.756,26.790,GrabPractice,HOVER_END,Cube,,FALSE,1.683,0.000,Section=GrabPractice,HoverDuration=1.683s\n',
 '2026-05-02 11:31:56.714,33.749,GrabPractice,HOVER_START,Sphere,,FALSE,0.000,0.000,Section=GrabPractice,IsCorrect=False\n',
 '2026-05-02 11:31:57.122,34.151,GrabPractice,GRAB_START,Sphere,Right,FALSE,0.000,0.000,Section=GrabPractice,Position=(0.84, 1.18, -0.01),WasHovered=True\n',
 '2026-05-02 11:31:58.603,35.637,GrabPractice,GRAB_RELEASE,Sphere,Right,FALSE,1.485,0.172,Section=GrabPractice,ReleasePos=(1.00, 1.22, -0.01),GripDuration=1.485s,WasHovered=True\n',
 '2026-05-02 11:31:58.769,35.803,GrabPractice,HOVER_END,Sphere,,FALSE,2.055,0.000,Section=GrabPractice,HoverDuration=2.055s\n',
 '2026-05-02 11:31:59.200,36.234,GrabPractice,HOVER_START,Sphere,,FALSE,0.000,0.000,Section=GrabPractice,IsCorrect=False\n',
 '2026-05-02 11:32:00.047,37.081,GrabPractice,GRAB_START,Sphere,Right,FALSE,0.000,0.000,Section=GrabPractice,Position=(0.84, 1.18, -0.01),WasHovered=True,InterObjectTime=2.93s\n',
 '2026-05-02 11:32:01.173,38.207,GrabPractice,GRAB_RELEASE,Sphere,Right,FALSE,1.125,0.219,Section=GrabPractice,ReleasePos=(1.05, 1.19, -0.02),GripDuration=1.125s,WasHovered=True\n',
 '2026-05-02 11:32:01.190,38.209,GrabPractice,HOVER_END,Sphere,,FALSE,1.975,0.000,Section=GrabPractice,HoverDuration=1.975s\n',
 '2026-05-02 11:32:01.191,38.209,GrabPractice,GRAB_PRACTICE_PLACEMENT,,,,0.000,0.000,Section=GrabPractice,ObjectsPlaced=1,Required=3\n',
 '2026-05-02 11:32:02.936,39.970,GrabPractice,HOVER_START,Cylinder,,FALSE,0.000,0.000,Section=GrabPractice,IsCorrect=False\n',
 '2026-05-02 11:32:03.311,40.346,GrabPractice,GRAB_START,Cylinder,Right,FALSE,0.000,0.000,Section=GrabPractice,Position=(0.83, 1.23, -0.26),WasHovered=True,InterObjectTime=3.26s\n',
 '2026-05-02 11:32:03.631,40.664,GrabPractice,GAZE_START,,,,0.000,0.000,Section=GrabPractice,Target=Cylinder,Distance=1.33m\n',
 '2026-05-02 11:32:03.853,40.887,GrabPractice,GAZE_END,,,,0.000,0.000,Section=GrabPractice,Target=Cylinder,DwellTime=0.22s,Distance=1.33m\n',
 '2026-05-02 11:32:03.964,40.997,GrabPractice,GAZE_START,,,,0.000,0.000,Section=GrabPractice,Target=Cylinder,Distance=1.42m\n',
 '2026-05-02 11:32:04.186,41.220,GrabPractice,GAZE_END,,,,0.000,0.000,Section=GrabPractice,Target=Cylinder,DwellTime=0.22s,Distance=1.42m\n',
 '2026-05-02 11:32:04.797,41.831,GrabPractice,GRAB_RELEASE,Cylinder,Right,FALSE,1.486,0.299,Section=GrabPractice,ReleasePos=(0.81, 1.25, -0.56),GripDuration=1.486s,WasHovered=True\n',
 '2026-05-02 11:32:04.825,41.849,GrabPractice,HOVER_END,Cylinder,,FALSE,1.879,0.000,Section=GrabPractice,HoverDuration=1.879s\n',
 '2026-05-02 11:32:04.826,41.849,GrabPractice,GRAB_PRACTICE_PLACEMENT,,,,0.000,0.000,Section=GrabPractice,ObjectsPlaced=2,Required=3\n',
 '2026-05-02 11:32:06.117,43.151,GrabPractice,HOVER_START,Cube,,FALSE,0.000,0.000,Section=GrabPractice,IsCorrect=False\n',
 '2026-05-02 11:32:06.159,43.193,GrabPractice,HOVER_END,Cube,,FALSE,0.042,0.000,Section=GrabPractice,HoverDuration=0.042s\n',
 '2026-05-02 11:32:06.172,43.207,GrabPractice,HOVER_START,Cube,,FALSE,0.000,0.000,Section=GrabPractice,IsCorrect=False\n',
 '2026-05-02 11:32:06.506,43.540,GrabPractice,GRAB_START,Cube,Right,FALSE,0.000,0.000,Section=GrabPractice,Position=(0.84, 1.18, 0.21),WasHovered=True,InterObjectTime=3.19s\n',
 '2026-05-02 11:32:07.992,45.027,GrabPractice,GRAB_RELEASE,Cube,Right,FALSE,1.487,0.347,Section=GrabPractice,ReleasePos=(0.79, 1.22, 0.55),GripDuration=1.487s,WasHovered=True\n',
 '2026-05-02 11:32:08.007,45.029,GrabPractice,HOVER_END,Cube,,FALSE,1.822,0.000,Section=GrabPractice,HoverDuration=1.822s\n',
 '2026-05-02 11:32:08.008,45.029,GrabPractice,GRAB_PRACTICE_PLACEMENT,,,,0.000,0.000,Section=GrabPractice,ObjectsPlaced=3,Required=3\n',
 '2026-05-02 11:32:09.006,46.040,GrabPractice,PANEL_DISMISSED,GrabInstructionPanel,,,21.000,0.000,Section=GrabPractice,Panel=GrabInstructionPanel,ReadingTime=21.00s\n',
 '2026-05-02 11:32:09.007,46.040,GrabPractice,GRAB_SECTION_COMPLETE,,,,0.000,0.000,Section=GrabPractice,CompletionTime=21.00s,ObjectsPlaced=3\n',
 '2026-05-02 11:32:09.007,46.040,GrabPractice,SECTION_END,,,,21.000,0.000,Section=GrabPractice,Duration=21.00s\n',
 '--- SECTION BREAK: Completion ---,,,,,,,\n',
 '2026-05-02 11:32:09.007,46.040,Completion,SECTION_START,,,,0.000,0.000,Section=Completion,PhaseTime=46.04s\n',
 '2026-05-02 11:32:09.008,46.040,Completion,TUTORIAL_COMPLETE,,,,0.000,0.000,Section=Completion,ObjectsPlaced=3,ButtonsPressed=2\n',
 '2026-05-02 11:32:12.007,49.040,Completion,SCORING_SUMMARY,,,,0.000,0.000,Section=Completion,Correct=0,Incorrect=0,Total=0,Accuracy=0.0%,Hovers=7\n',
 '2026-05-02 11:32:12.007,49.040,Completion,PHASE_END,,,,49.040,0.000,Samples=442,Events=77\n']

In [26]:
with open(file_path, "r", encoding="utf-8") as f:
    # read all lines from the file
    lines = f.readlines()

# extract the first line (header) and split it into columns
columns_line = lines[0]
columns = columns_line.strip().split(",")
lines.pop(0)  # remove the header line from the list of lines
columns.append("Activity_Log")
print(columns)

# separate lines based on the section break
pattern = r"^--- SECTION BREAK:"
section_lines = []

for line in lines:
    if re.match(pattern, line):
        #df = pd.DataFrame(section_lines, columns=columns)
        break
    section_lines.append(line)

print(section_lines)

['Timestamp', 'PhaseTime_s', 'Section', 'EventType', 'ObjectName', 'Hand', 'IsCorrect', 'Duration_s', 'Distance_m', 'Details', 'Activity_Log']
['2026-05-02 11:31:17.628,0.000,Default,PHASE_START,,,,0.000,0.000,Phase=01_Tutorial,Section=Default,SessionID=20260502_113117,PatientID=,SampleRate=10Hz,Device=Oculus Quest 3,GazeTrackerActive=True\n', '2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,,,0.000,0.000,Section=Default,Panel=WelcomePanel\n', '2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=1\n', '2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.95s\n', '2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=2\n', '2026-05-02 11:31:26.183,3.217,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.11s\n', '2026-05-02 11:31:26.378,3.411,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=3\n', '2026-05-02 11:31:26.697,3.731,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.32s\n', '2026-05-02 11:31:28.907,5.940,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=4\n', '2026-05-02 11:31:29.448,6.483,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.54s\n', '2026-05-02 11:31:35.603,12.637,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=5\n', '2026-05-02 11:31:37.895,14.930,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=2.29s\n', '2026-05-02 11:31:38.423,15.457,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=6\n', '2026-05-02 11:31:38.909,15.943,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.49s\n', '2026-05-02 11:31:39.381,16.415,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=7\n', '2026-05-02 11:31:39.979,17.013,Default,BUTTON_PRESSED,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],PressTime=0.60s\n', '2026-05-02 11:31:40.200,17.235,Default,BUTTON_RELEASED,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],PressDuration=0.222s\n', '2026-05-02 11:31:40.205,17.235,Default,PANEL_DISMISSED,WelcomePanel,,,17.235,0.000,Section=Default,Panel=WelcomePanel,ReadingTime=17.23s\n', '2026-05-02 11:31:40.206,17.235,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.82s\n', '2026-05-02 11:31:40.208,17.235,Default,SECTION_END,,,,17.235,0.000,Section=Default,Duration=17.23s\n']

In [8]:
len(section_lines)

20

In [9]:
section_lines

['2026-05-02 11:31:17.628,0.000,Default,PHASE_START,,,,0.000,0.000,Phase=01_Tutorial,Section=Default,SessionID=20260502_113117,PatientID=,SampleRate=10Hz,Device=Oculus Quest 3,GazeTrackerActive=True\n',
 '2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,,,0.000,0.000,Section=Default,Panel=WelcomePanel\n',
 '2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=1\n',
 '2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.95s\n',
 '2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=2\n',
 '2026-05-02 11:31:26.183,3.217,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.11s\n',
 '2026-05-02 11:31:26.378,3.411,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=3\n',
 '2026-05-02 11:31:26.697,3.731,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.32s\n',
 '2026-05-02 11:31:28.907,5.940,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=4\n',
 '2026-05-02 11:31:29.448,6.483,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.54s\n',
 '2026-05-02 11:31:35.603,12.637,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=5\n',
 '2026-05-02 11:31:37.895,14.930,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=2.29s\n',
 '2026-05-02 11:31:38.423,15.457,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=6\n',
 '2026-05-02 11:31:38.909,15.943,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.49s\n',
 '2026-05-02 11:31:39.381,16.415,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=7\n',
 '2026-05-02 11:31:39.979,17.013,Default,BUTTON_PRESSED,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],PressTime=0.60s\n',
 '2026-05-02 11:31:40.200,17.235,Default,BUTTON_RELEASED,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],PressDuration=0.222s\n',
 '2026-05-02 11:31:40.205,17.235,Default,PANEL_DISMISSED,WelcomePanel,,,17.235,0.000,Section=Default,Panel=WelcomePanel,ReadingTime=17.23s\n',
 '2026-05-02 11:31:40.206,17.235,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.82s\n',
 '2026-05-02 11:31:40.208,17.235,Default,SECTION_END,,,,17.235,0.000,Section=Default,Duration=17.23s\n']

In [27]:
cleaned_section_lines = []
for line in section_lines:
    messy_row = line.strip().split(",")
    messy_row[10] = messy_row[10:]
    del messy_row[11:]
    cleaned_section_lines.append(messy_row)

In [19]:
len(cleaned_section_lines)

20

In [28]:
cleaned_section_lines[0]

['2026-05-02 11:31:17.628',
 '0.000',
 'Default',
 'PHASE_START',
 '',
 '',
 '',
 '0.000',
 '0.000',
 'Phase=01_Tutorial',
 ['Section=Default',
  'SessionID=20260502_113117',
  'PatientID=',
  'SampleRate=10Hz',
  'Device=Oculus Quest 3',
  'GazeTrackerActive=True']]

In [29]:
df = pd.DataFrame(cleaned_section_lines, columns=columns)

In [38]:
df['Section'].unique()[0]

'Default'

In [30]:
df

,Timestamp,PhaseTime_s,Section,EventType,ObjectName,Hand,IsCorrect,Duration_s,Distance_m,Details,Activity_Log
0,2026-05-02 11:31:17.628,0.000,Default,PHASE_START,,,,0.000,0.000,Phase=01_Tutorial,"[Section=Default, SessionID=20260502_113117, P..."
1,2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,,,0.000,0.000,Section=Default,[Panel=WelcomePanel]
2,2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
3,2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
4,2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
5,2026-05-02 11:31:26.183,3.217,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
6,2026-05-02 11:31:26.378,3.411,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
7,2026-05-02 11:31:26.697,3.731,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
8,2026-05-02 11:31:28.907,5.940,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
9,2026-05-02 11:31:29.448,6.483,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
10,2026-05-02 11:31:35.603,12.637,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
11,2026-05-02 11:31:37.895,14.930,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
12,2026-05-02 11:31:38.423,15.457,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
13,2026-05-02 11:31:38.909,15.943,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
14,2026-05-02 11:31:39.381,16.415,Default,BUTTON_HOVER_START,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
15,2026-05-02 11:31:39.979,17.013,Default,BUTTON_PRESSED,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
16,2026-05-02 11:31:40.200,17.235,Default,BUTTON_RELEASED,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
17,2026-05-02 11:31:40.205,17.235,Default,PANEL_DISMISSED,WelcomePanel,,,17.235,0.000,Section=Default,"[Panel=WelcomePanel, ReadingTime=17.23s]"
18,2026-05-02 11:31:40.206,17.235,Default,BUTTON_HOVER_END,,,,0.000,0.000,Section=Default,"[Button=StartTutorialButton[TutorialWelcome], ..."
19,2026-05-02 11:31:40.208,17.235,Default,SECTION_END,,,,17.235,0.000,Section=Default,[Duration=17.23s]

In [31]:
df.to_csv('../../data/cleaned_data.csv', index=False)

In [63]:
x = selected_lines[0].strip().split(",")
x

['2026-05-02 11:31:17.628',
 '0.000',
 'Default',
 'PHASE_START',
 '',
 '',
 '',
 '0.000',
 '0.000',
 'Phase=01_Tutorial',
 'Section=Default',
 'SessionID=20260502_113117',
 'PatientID=',
 'SampleRate=10Hz',
 'Device=Oculus Quest 3',
 'GazeTrackerActive=True']

In [67]:
x[10] = x[10:]

In [68]:
x[10]

['Section=Default',
 'SessionID=20260502_113117',
 'PatientID=',
 'SampleRate=10Hz',
 'Device=Oculus Quest 3',
 'GazeTrackerActive=True']

In [30]:
tutorial_events.columns

Index(['Timestamp', 'PhaseTime_s', 'Section', 'EventType', 'ObjectName',
       'Hand', 'IsCorrect', 'Duration_s', 'Distance_m', 'Details'],
      dtype='object')

In [31]:
tutorial_events.shape

(81, 10)

In [32]:
tutorial_events.head()

,,,,,,Timestamp,PhaseTime_s,Section,EventType,ObjectName,Hand,IsCorrect,Duration_s,Distance_m,Details
2026-05-02 11:31:17.628,0.000,Default,PHASE_START,NaN,NaN,NaN,0.0,0.0,Phase=01_Tutorial,Section=Default,SessionID=20260502_113117,PatientID=,SampleRate=10Hz,Device=Oculus Quest 3,GazeTrackerActive=True
2026-05-02 11:31:17.630,0.000,Default,PANEL_SHOWN,WelcomePanel,NaN,NaN,0.0,0.0,Section=Default,Panel=WelcomePanel,NaN,NaN,NaN,NaN,NaN
2026-05-02 11:31:22.971,0.000,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=1,NaN,NaN,NaN,NaN
2026-05-02 11:31:23.918,0.952,Default,BUTTON_HOVER_END,NaN,NaN,NaN,0.0,0.0,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverDuration=0.95s,NaN,NaN,NaN,NaN
2026-05-02 11:31:26.072,3.106,Default,BUTTON_HOVER_START,NaN,NaN,NaN,0.0,0.0,Section=Default,Button=StartTutorialButton[TutorialWelcome],HoverCount=2,NaN,NaN,NaN,NaN

In [33]:
separator_indices = tutorial_events.index[tutorial_events.iloc[:,0] == "--- SECTION BREAK: ButtonSelection ---,,,,,,,"].tolist()

In [34]:
separator_indices

[]

In [22]:
tutorial_events.iloc[22,:]

Timestamp                               NaN
PhaseTime_s                             0.0
Section                                 0.0
EventType           Section=ButtonSelection
ObjectName     Panel=ButtonInstructionPanel
Hand                                    NaN
IsCorrect                               NaN
Duration_s                              NaN
Distance_m                              NaN
Details                                 NaN
Name: (2026-05-02 11:31:40.209, 17.235, ButtonSelection, PANEL_SHOWN, ButtonInstructionPanel, nan), dtype: object

In [11]:
rows = tutorial_events[tutorial_events.iloc[:, :] == "--- SECTION BREAK"]

In [12]:
rows

                                                                                        Timestamp  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN       NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN       NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN       NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN       NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN       NaN
...                                                                                           ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN       NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN       NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN       NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN       NaN
                                                    PHASE_END          NaN          NaN       NaN

                                                                                         PhaseTime_s  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN          NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN          NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN          NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN          NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN          NaN
...                                                                                              ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN          NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN          NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN          NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN          NaN
                                                    PHASE_END          NaN          NaN          NaN

                                                                                         Section  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN      NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN      NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN      NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN      NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN      NaN
...                                                                                          ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN      NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN      NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN      NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN      NaN
                                                    PHASE_END          NaN          NaN      NaN

                                                                                        EventType  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN       NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN       NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN       NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN       NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN       NaN
...                                                                                           ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN       NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN       NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN       NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN       NaN
                                                    PHASE_END          NaN          NaN       NaN

                                                                                        ObjectName  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN        NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN        NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN        NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN        NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN        NaN
...                                                                                            ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN        NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN        NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN        NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN        NaN
                                                    PHASE_END          NaN          NaN        NaN

                                                                                        Hand  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN  NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN  NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN  NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN  NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN  NaN
...                                                                                      ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN  NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN  NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN  NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN  NaN
                                                    PHASE_END          NaN          NaN  NaN

                                                                                        IsCorrect  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN       NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN       NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN       NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN       NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN       NaN
...                                                                                           ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN       NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN       NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN       NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN       NaN
                                                    PHASE_END          NaN          NaN       NaN

                                                                                        Duration_s  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN        NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN        NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN        NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN        NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN        NaN
...                                                                                            ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN        NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN        NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN        NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN        NaN
                                                    PHASE_END          NaN          NaN        NaN

                                                                                        Distance_m  \
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN        NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN        NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN        NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN        NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN        NaN
...                                                                                            ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN        NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN        NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN        NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN        NaN
                                                    PHASE_END          NaN          NaN        NaN

                                                                                        Details
2026-05-02 11:31:17.628           0.000  Default    PHASE_START        NaN          NaN     NaN
2026-05-02 11:31:17.630           0.000  Default    PANEL_SHOWN        WelcomePanel NaN     NaN
2026-05-02 11:31:22.971           0.000  Default    BUTTON_HOVER_START NaN          NaN     NaN
2026-05-02 11:31:23.918           0.952  Default    BUTTON_HOVER_END   NaN          NaN     NaN
2026-05-02 11:31:26.072           3.106  Default    BUTTON_HOVER_START NaN          NaN     NaN
...                                                                                         ...
--- SECTION BREAK: Completion --- NaN    NaN        NaN                NaN          NaN     NaN
2026-05-02 11:32:09.007           46.040 Completion SECTION_START      NaN          NaN     NaN
2026-05-02 11:32:09.008           46.040 Completion TUTORIAL_COMPLETE  NaN          NaN     NaN
2026-05-02 11:32:12.007           49.040 Completion SCORING_SUMMARY    NaN          NaN     NaN
                                                    PHASE_END          NaN          NaN     NaN

[81 rows x 10 columns]

In [8]:
import pandas as pd

# Read the CSV
#df = pd.read_csv("input.csv", header=None)
df = tutorial_events.copy()  # Using the tutorial_events DataFrame for demonstration
# Find rows containing the separator
separator = "--- SECTION BREAK"

# Create groups based on separator occurrences
groups = (df[0] == separator).cumsum()

# Remove separator rows
df_clean = df[df[0] != separator]

# Split and save
for i, (_, group) in enumerate(df_clean.groupby(groups[df_clean.index]), start=1):
    output_file = f"output_{i}.csv"
    group.to_csv(output_file, index=False, header=False)

    print(f"Created: {output_file}")

KeyError: 0

In [ ]:
# break the csv file into smaller files
separator = "--- SECTION BREAK"